# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//bazel/pytest:defs.bzl", "pytest_test")

package(default_visibility = [
    "//:core_package_group",
    "//bazel/docs:__pkg__",
])

filegroup(
    name = "py_files",
    srcs = glob(["**/*.py"]),
    visibility = [
    ],
)

py_library(
    name = "pylib",
    srcs = [
        "__init__.py",
        "model.py",
        "training_controller.py",
        "utils.py",
    ],
    deps = [
        "//nre/config:pylib",
        "//nre/utils:pylib",
        "//nre/utils:pylib_schedulers",
        "//nre/utils:pylib_types",
        pip_requirement("torch"),
        pip_requirement("einops"),
        pip_requirement("torchvision"),
        pip_requirement("kornia"),
        pip_requirement("transformer_engine"),
        pip_requirement("numpy"),
    ],
)

pytest_test(
    name = "difix_test",
    srcs = [
        "difix_test.py",
    ],
    deps = [
        ":pylib",
        "//nre/systems:utils",
        pip_requirement("omegaconf"),
    ],
)
