# SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@rules_python//python:defs.bzl", "py_library")

DEFAULT_VISIBILITY = ["//:core_package_group"]

package(default_visibility = DEFAULT_VISIBILITY)

filegroup(
    name = "py_files",
    srcs = glob(["**/*.py"]),
    visibility = [
    ],
)

py_library(
    name = "pylib_packed_ops_torch",
    srcs = ["_packed_ops_torch.py"],
    deps = [
        pip_requirement("torch"),
    ],
)

py_library(
    name = "pylib_packed_ops",
    srcs = ["packed_ops.py"],
    deps = [
        ":pylib_packed_ops_torch",
        pip_requirement("torch"),
    ],
)

py_library(
    name = "pylib_types",
    srcs = [
        "batch.py",
        "types.py",
    ],
    visibility = DEFAULT_VISIBILITY + [
        # Add visibility for //internal/scripts/experimental:grpc_control_actors and :ncore_to_ngp
        # Add visibility for nvhuman animation scripts
        # Add visibility for aux_gen ncore_aux_data
    ],
    deps = [
        ":pylib_geometry",
        ":pylib_misc",
        ":pylib_se3_torch",
        "//instant_nurec/_pkg/utils/sensors:pylib",
        "//instant_nurec/_pkg/utils/sensors:pylib_ncore_sensors_converters",
        pip_requirement("numpy"),
        pip_requirement("nvidia-ncore"),
        pip_requirement("torch"),
        pip_requirement("usd-core"),
    ],
)

py_library(
    name = "pylib_misc",
    srcs = ["misc.py"],
    visibility = DEFAULT_VISIBILITY + [
        # Add visibility for //internal/workflows
        # Add visibility for nvhuman animation scripts
    ],
    deps = [
        pip_requirement("numpy"),
        pip_requirement("torch"),
    ],
)

py_library(
    name = "pylib_ncore_utils",
    srcs = ["ncore_utils.py"],
    visibility = [
        "//:aux_package_group",
        "//:core_package_group",
    ],
    deps = [
        ":pylib_types",
        pip_requirement("nvidia-ncore"),
        pip_requirement("numpy"),
        pip_requirement("pillow"),
        pip_requirement("torch"),
        pip_requirement("torchvision"),
        pip_requirement("universal-pathlib"),
        pip_requirement("zarr"),
    ],
)

py_library(
    name = "pylib_se3_torch",
    srcs = ["_se3_torch.py"],
    visibility = DEFAULT_VISIBILITY,
    deps = [
        pip_requirement("torch"),
    ],
)

py_library(
    name = "pylib_geometry",
    srcs = [
        "geometry.py",
    ],
    visibility = DEFAULT_VISIBILITY + [
        # Add visibility for nvhuman animation scripts
        # Add visibility for aux_gen estimators
    ],
    deps = [
        pip_requirement("torch"),
        pip_requirement("numpy"),
    ],
)

py_library(
    name = "pylib",
    srcs = [
        "__init__.py",
        "lidar_model.py",
        "model_registry.py",
    ],
    visibility = DEFAULT_VISIBILITY + [
        # Add visibility for //internal/scripts/ncore_vis:ncore_vis
        # Add visibility for //internal/scripts/ncore:ncore_sequence_chunks
        # Add visibility for //internal/scripts/experimental:render
        # Add visibility for //internal/scripts/ngc:download_model
        # Add visibility for //internal/scripts/ds2ncore
        # Add visibility for //apps/asset_harvester
    ],
    deps = [
        ":pylib_geometry",
        ":pylib_misc",
        ":pylib_packed_ops",
        ":pylib_types",
        "//instant_nurec/_pkg:pylib",
        "//instant_nurec/_pkg/config:pylib",
        pip_requirement("torch"),
        pip_requirement("nvidia-ncore"),
        pip_requirement("numpy"),
        pip_requirement("matplotlib"),
        pip_requirement("flow_vis"),
        pip_requirement("scipy"),
        pip_requirement("shortuuid"),
        pip_requirement("tensorboardx"),
        pip_requirement("pydantic"),
        pip_requirement("pillow"),
        pip_requirement("point-cloud-utils"),
        pip_requirement("wandb"),
        pip_requirement("pyyaml"),
        pip_requirement("requests"),
        pip_requirement("tqdm"),
        pip_requirement("tinycudann"),
    ],
)

py_library(
    name = "pylib_files",
    srcs = [
        "files.py",
    ],
    visibility = DEFAULT_VISIBILITY + [
    ],
    deps = [
        pip_requirement("universal-pathlib"),
    ],
)

py_binary(
    name = "ffmpeg_wrap",
    srcs = [
        "ffmpeg_wrap.py",
    ],
    main = "ffmpeg_wrap.py",
    deps = [
        pip_requirement("imageio-ffmpeg"),
        pip_requirement("setuptools"),
    ],
)

py_library(
    name = "pylib_gaussian_render",
    srcs = [
        "gaussian_render.py",
    ],
    visibility = DEFAULT_VISIBILITY + [
    ],
    deps = [
        ":pylib_geometry",
        "//instant_nurec/_pkg/models/gaussians:pylib",
        pip_requirement("imageio"),
        pip_requirement("kiui"),
        pip_requirement("numpy"),
        pip_requirement("torch"),
    ],
)
