# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@rules_shell//shell:sh_test.bzl", "sh_test")

# Test to make sure only absolute paths are used in python files (requirement for pycena obfuscation)
sh_test(
    name = "python_absolute_path_check",
    srcs = ["check_absolute_paths.sh"],
    data = [
        "//:run",
        "//apps/aux_gen:ncore_aux_data",
    ],
)
