# @package _global_
# Owner: Haithem Turki

model:
  renderer:
    per_ray_features: false
    # enable ray gradients backpropagation for both lidar and camera
    outputs:
      lidar:
        enable_ray_gradients: true
      camera:
        enable_ray_gradients: true

  calib:
    name: free-pose-calib
    lidar:
      enabled: true
    camera:
      enabled: true
