# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

DEFAULT_VISIBILITY = ["//:core_package_group"]

package(default_visibility = DEFAULT_VISIBILITY)

filegroup(
    name = "testdata",
    srcs = [
        "catalog.json",
    ] + glob(["scenarios/*.json"]),
    visibility = [
        "//internal/sqa:__pkg__",
        "//internal/sqa/test_cases:__pkg__",
    ],
)

filegroup(
    name = "samples",
    srcs = glob(["samples/*"]),
    visibility = [
        "//internal/sqa:__pkg__",
        "//internal/sqa/test_cases:__pkg__",
    ],
)
