# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@rules_cc//cc:defs.bzl", "cc_binary")
load("@rules_cuda//cuda:defs.bzl", "cuda_library")
load("@rules_python//python:defs.bzl", "py_library")
load("//bazel/pytest:defs.bzl", "pytest_test")

DEFAULT_VISIBILITY = ["//:core_package_group"]

package(default_visibility = DEFAULT_VISIBILITY)

filegroup(
    name = "py_files",
    srcs = glob(["*.py"]),
)

cuda_library(
    name = "gaussian_mcmc_cuda",
    srcs = [
        "gaussian_mcmc.cu",
    ],
    hdrs = [
        "utils.h",
    ],
    copts = [
        # Flags to be consistent with torch-cuda-extensions
        "-D__CUDA_NO_HALF_OPERATORS__",
        "-D__CUDA_NO_HALF_CONVERSIONS__",
        "-D__CUDA_NO_BFLOAT16_CONVERSIONS__",
        "-D__CUDA_NO_HALF2_OPERATORS__",
    ],
    deps = [
        "//libs/kernel_utils:ku_cc",
        "//libs/kernel_utils:ku_cuda",
        "@nre_pip_deps//torch:torch_headers",
        "@rules_python//python/cc:current_py_cc_headers",
    ],
)

cc_binary(
    name = "gaussian_mcmc_cc",
    srcs = ["binding.cpp"],
    copts = [
        # Flags to be consistent with torch-cuda-extensions and to build correct torch-extension bindings
        "-DTORCH_API_INCLUDE_EXTENSION_H",
        "-DTORCH_EXTENSION_NAME=libgaussian_mcmc_cc",
    ],
    linkopts = [
        "-Wl,--no-undefined",
        "-Wl,--as-needed",
    ],
    linkshared = True,
    deps = [
        ":gaussian_mcmc_cuda",
        "//libs/kernel_utils:ku_cc",
        "@nre_pip_deps//torch:libc10",
        "@nre_pip_deps//torch:libc10_cuda",
        "@nre_pip_deps//torch:libtorch_cpu",
        "@nre_pip_deps//torch:libtorch_python",
        "@nre_pip_deps//torch:torch_headers",
        "@rules_python//python/cc:current_py_cc_libs",
    ],
)

py_library(
    name = "pylib_cc",
    srcs = [
        "__init__.py",
        "interface.py",
    ],
    data = [
        ":gaussian_mcmc_cc",
    ],
    visibility = DEFAULT_VISIBILITY + [
        "//bazel/docs:__pkg__",
    ],
    deps = [
        pip_requirement("torch"),
    ],
)

pytest_test(
    name = "gaussian_mcmc_test",
    srcs = ["gaussian_mcmc_test.py"],
    deps = [
        ":pylib_cc",
        pip_requirement("torch"),
        pip_requirement("parameterized"),
        "//libs:pylib",
        "//nre/utils:pylib_geometry",
        "//nre/utils:pylib_tests",
    ],
)
