# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@mypy_integration//:mypy.bzl", "mypy_test")

package(default_visibility = [":__subpackages__"])

py_binary(
    name = "run_ndas_workflow",
    srcs = [
        "run_ndas_workflow.py",
    ],
    data = [
        "//internal/workflows/cluster_toolbox/cluster_configs",
        "@maglev_cli//file:maglev",
    ],
    main = "run_ndas_workflow.py",
    deps = [
        "//internal/workflows/cluster_toolbox:pylib",
    ],
)

mypy_test(
    name = "run_ndas_mypy",
    timeout = "long",
    deps = [
        ":run_ndas_workflow",
    ],
)
