# SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//bazel/pytest:defs.bzl", "pytest_test")

DEFAULT_VISIBILITY = [
    "//:core_package_group",
    "//bazel/docs:__pkg__",
]

package(default_visibility = DEFAULT_VISIBILITY)

filegroup(
    name = "py_files",
    srcs = glob(["**/*.py"]),
    visibility = [
    ],
)

# TODO: Seperate ncore files into their own self-contained py_library
py_library(
    name = "pylib",
    srcs = [
        "__init__.py",
        "base.py",
        "labels_utils.py",
        "ncore.py",
        "registry.py",
        "summary.py",
        "utils.py",
    ],
    visibility = DEFAULT_VISIBILITY + [
        # Add visibility for //internal/scripts/experimental:ncore_to_ngp
        # Allow scripts (including asset_harvester) to depend on datasets pylib
    ],
    deps = [
        pip_requirement("scipy"),
        pip_requirement("nvidia-ncore"),
        pip_requirement("nvidia-ncore-internal"),
        pip_requirement("opencv-python"),
        pip_requirement("imageio"),
        pip_requirement("imageio-ffmpeg"),
        pip_requirement("setuptools"),
        pip_requirement("einops"),
        pip_requirement("tqdm"),
        pip_requirement("numpy"),
        pip_requirement("torch"),
        pip_requirement("omegaconf"),
        pip_requirement("lietorch"),
        pip_requirement("pillow"),
        pip_requirement("pandas"),
        pip_requirement("universal-pathlib"),
        pip_requirement("dataclasses-json"),
        pip_requirement("simplejpeg"),
        pip_requirement("cuml-cu12"),
        ":pylib_tracks",
        "//libs/vren:pylib",
        "//libs/vren:pylib_cc",
        "//nre/config:pylib",
        "//nre/datasets/samplers:pylib",
        "//nre/utils:pylib",
        "//nre/utils:pylib_morph",
        "//nre/utils:pylib_ncore_utils",
    ],
)

pytest_test(
    name = "utils_test",
    srcs = ["utils_test.py"],
    deps = [
        ":pylib",
    ],
)

py_library(
    name = "pylib_tracks",
    srcs = [
        "tracks.py",
    ],
    deps = [
        pip_requirement("torch"),
        pip_requirement("numpy"),
        pip_requirement("dataclasses-json"),
        "//libs/vren:pylib_cc",
        "//nre/utils:pylib",
        "//nre/utils:pylib_fields",
    ],
)

pytest_test(
    name = "tracks_test",
    srcs = ["tracks_test.py"],
    deps = [
        pip_requirement("torch"),
        pip_requirement("numpy"),
        ":pylib_tracks",
        "//nre/models:pylib",
        "//nre/utils:pylib",
        "//nre/utils:pylib_tests",
    ],
)
