[repo_docs]
enabled = true
project = "nurec"
name = "NVIDIA Omniverse NuRec"
docs_root = "${root}"

copyright_start = 2024
version = "1.0"

myst_enable_extensions = [
    "replacements",
    "substitution",
]
