# SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")

DEFAULT_VISIBILITY = ["//:core_package_group"]

package(default_visibility = DEFAULT_VISIBILITY)

filegroup(
    name = "scripts",
    srcs = glob(["*.sh"]) + [
        "resolve_edit_assets_scenario.py",
    ],
    visibility = [
        "//internal/sqa:__pkg__",  # Allow sqa package to see it
        "//internal/sqa/test_cases:__pkg__",  # Keep existing visibility for test package
    ],
)

py_binary(
    name = "create_comparison_gif",
    srcs = ["create_comparison_gif.py"],
    main = "create_comparison_gif.py",
    visibility = [
        "//internal/sqa:__pkg__",
    ],
    deps = [
        pip_requirement("click"),
        pip_requirement("pillow"),
    ],
)
