defaults:
  - gaussians

background:
  fn: mse
  reduce:
    name: mean
  lambda_: ${eval:'0.05 if ("${model.background.name}"=="sky-mlp" or "${model.background.name}"=="extra-signal-sky-mlp" or "${model.background.name}"=="sky-env-map") else 0.0'}
background_lidar:
  fn: mse
  reduce:
    name: mean
  lambda_: ${eval:'0.05 if ("${model.background.name}"=="sky-mlp" or "${model.background.name}"=="extra-signal-sky-mlp" or "${model.background.name}"=="sky-env-map") else 0.0'}
sky_env_map_background:
  fn: total_variation_spatial
  reduce:
    name: mean
  lambda_: ${eval:'1e-2 if "${model.background.name}"=="sky-env-map" else 0.0'}
lidar:
  fn: l1
  reduce:
    name: mean
  lambda_: 0.0003
bilateral_grid_per_frame_spatial_tv:
  fn: total_variation_spatial
  reduce:
    name: mean
  # Per-frame bilateral grids are allowed be less smooth compared to per-camera,
  # e.g., to model effects such as internal lens reflections.
  lambda_: 0.001
bilateral_grid_per_frame_temporal_tv:
  fn: total_variation_temporal
  reduce:
    name: mean
  lambda_: 1.0
bilateral_grid_per_camera_tv:
  fn: total_variation_spatial
  reduce:
    name: mean
  lambda_: 0.001
bilateral_grid_drift:
  fn: identity_distance
  reduce:
    name: mean
  lambda_: 0.001
ppisp:
  fn: ppisp_loss
  reduce:
    name: mean
  lambda_: 1.0 # Top-level lambda. Note that lambdas for individual losses are listed below:
  lambdas:
    exposure_mean: 0.001 # Pushes mean exposure offsets across frames to zero
    exposure_smooth: 1.0 # Ensures smoothness of exposure offsets across frames of the same camera
    vig_center: 0.02 # Pushes the vignetting center ("optical center") towards (0.5, 0.5)
    vig_channel: 0.01 # Ensures vignetting across RGB channels has similar parameters
    vig_non_pos: 0.01 # Ensures alpha values are non-positive
    color_mean: 0.01 # Pushes mean color correction across frames to no correction
    color_smooth: 1.0 # Ensures smoothness of color corrections across frames of the same camera
    crf_range: 0.01 # Pushes the maximum dynamic range to 1, ensuring LDR tone compression
    crf_gamma: 0.001 # Pushes the CRF curve gamma value to 1/2.2 (similar to sRGB)
    crf_channel: 0.01 # Ensures CRF across RGB channels has similar parameters
deform_smoothness:
  fn: abs
  reduce:
    name: mean
  lambda_: 0.01
out_of_bound:
  fn: l1
  reduce:
    name: mean
  lambda_: 1
background_in_track_gaussian:
  fn: bce_with_logits
  reduce:
    name: mean
  lambda_: 0.1
  layer_names:
    - background  # layer name to suppress
  # layer_labels_to_use: semantic classes to penalize for each layer in layer_names, if layer_name not in layer_labels_to_use, use all gaussians in the layer
  # e.g., {background: [person, rider, car, truck, bus, train, motorcycle, bicycle]}  # only penalize these dynamic classes in background layer
  layer_labels_to_use: {}  # default empty dict disables semantic classes, penalize all gaussians in each layer in layer_names
  density_logits_min: -20.0  # Minimum pre-activation density bound (e.g., -20 => sigmoid(-20) ~ 1e-9).
semantic: # uses the semantic maps as labels
  fn: cross_entropy
  reduce:
    name: mean
  lambda_: 0.0 # disabled by default - suggested default weight is 0.001 when enabled
  start_step: 1000 # suggested to start training late to promote stability
intensity:
  fn: mse
  reduce:
    name: mean
  lambda_: 0.0  # disabled by default - suggested default weight is 1.0 when enabled  
raydrop:
  fn: mse #bce_truncated
  reduce:
    name: mean
  lambda_: 0.0  # disabled by default - suggested default weight is 1.0 when enabled  
normal:
  fn: l1
  reduce:
    name: mean
  lambda_: 0.0  # disabled by default - suggested default weight is 0.1 when enabled 
gaussian_flatten:
  fn: abs
  reduce:
    name: mean
  axes_type: fixed  # choose from [fixed, free]
  max_to_median_ratio_threshold: 1.0
  allow_missing_supervision: false
  lambda_: 0.0  # disabled by default - suggested default weight is 0.005 when enabled 
