#!/bin/bash
# Copyright (c) 2024-2026 NVIDIA CORPORATION.  All rights reserved.

set -euo pipefail

# Initialize runfiles support per
# https://github.com/bazelbuild/bazel/blob/8.3.1/tools/bash/runfiles/runfiles.bash
# for RUNFILES.Create() to behave as expected.
#
# In the non-obfuscated code, this is happening indirectly in the boostrap code
# generated by rules_py's "run.tmpl.sh" file, with the same snippet as below.
#
# --- begin runfiles.bash initialization v3 ---
# Copy-pasted from the Bazel Bash runfiles library v3.
set -uo pipefail; set +e; f=bazel_tools/tools/bash/runfiles/runfiles.bash
# shellcheck disable=SC1090
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \
  source "$0.runfiles/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  { echo>&2 "ERROR: cannot find $f"; exit 1; }; f=; set -e
# --- end runfiles.bash initialization v3 ---
runfiles_export_envvars

# Find the pre-built venv directory from the py_venv_binary target
# py_venv_binary creates the venv at build time, so we just need to activate it.
VENV_DIR=$(find -L "${RUNFILES_DIR}/_main/internal/scripts/pycena/runtime" -maxdepth 1 -type d -name "pycena_*_venv_deps.venv" -print -quit 2>/dev/null)
if [[ -z "${VENV_DIR}" ]]; then
    echo>&2 "ERROR: Could not find venv directory in runfiles"
    exit 1
fi

# Activate the pre-built venv (same approach as py_venv_binary entrypoint)
source "${VENV_DIR}/bin/activate"

# Point the embedded CPython in pycena_*_cc at the hermetic toolchain in runfiles.
# The toolchain is built with prefix=/install; that path doesn't exist in Bazel
# sandboxes, so PYTHONHOME must redirect it to the runfiles copy so it finds stdlib.
_PYTHON_PREFIX_KEY=$(grep "^aspect-runfiles-interpreter" "${VENV_DIR}/pyvenv.cfg" | cut -d= -f2 | xargs dirname | xargs dirname)
export PYTHONHOME="$(rlocation "$_PYTHON_PREFIX_KEY")"

# Add venv to PATH (so `python3` resolves to the venv's python)
PATH="${VIRTUAL_ENV}/bin:${PATH}"
export PATH

# For the embedded Python in the obfuscated binary:
# The venv's site-packages includes pip packages.
# We need to add to PYTHONPATH:
# 1. _main at the front (so project modules take precedence)
# 2. rules_python+ (for python.runfiles module used by obfuscated code)
# 3. External repos (+*_repo*) containing packages like gsplat
# 4. venv site-packages
MAIN_DIR="$(rlocation _main)"
RULES_PYTHON_DIR="$(rlocation rules_python+)"
SITE_PACKAGES="${VIRTUAL_ENV}/lib/python3.11/site-packages"
PYTHONPATH="${MAIN_DIR}:${RULES_PYTHON_DIR}"
for dir in "${RUNFILES_DIR}"/+*_repo*/; do
    if [[ -d "$dir" ]]; then
        PYTHONPATH="${PYTHONPATH}:${dir}"
    fi
done
PYTHONPATH="${PYTHONPATH}:${SITE_PACKAGES}"
export PYTHONPATH

# Get Python include path for SlangTorch JIT compilation
PYINCLUDE="$(${VIRTUAL_ENV}/bin/python3 -c 'import sysconfig; print(sysconfig.get_path("include"))')"
if [ -z "${CPATH-}" ]; then
    export CPATH=$PYINCLUDE
else
    export CPATH=$PYINCLUDE:$CPATH
fi
export CPLUS_INCLUDE_PATH=$CPATH

# Enter the _main directory in the runfiles tree
cd $(rlocation _main)

# Call obfuscated target (an obfuscated script binary), passing other arguments to this binary
$(find internal/scripts/pycena -executable -name pycena_*_cc -print -quit) "$@"
