# SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@mypy_integration//:mypy.bzl", "mypy_test")
load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@nre_pip_deps_internal//:requirements.bzl", pip_requirement_internal = "requirement")

py_binary(
    name = "ncore_sequence_chunks",
    srcs = [
        "ncore_sequence_chunks.py",
    ],
    main = "ncore_sequence_chunks.py",
    deps = [
        "//nre/utils:pylib",
        pip_requirement("click"),
        pip_requirement("numpy"),
        pip_requirement("nvidia-ncore"),
        pip_requirement("nvidia-ncore-internal"),
        pip_requirement_internal("polyscope"),
    ],
)

mypy_test(
    name = "ncore_sequence_chunks_mypy",
    timeout = "long",
    deps = [
        ":ncore_sequence_chunks",
    ],
)
