# Copyright (c) 2023-2026 NVIDIA CORPORATION.  All rights reserved.

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .ci-keep
  FF_TIMESTAMPS: true # Enable timestamps in job logs
  BASH_ENV: "$CI_PROJECT_DIR/internal/scripts/ci/bazelisk_telemetry.sh" # Bazelisk wrapper function to capture BEP and profile data
  AUTO_RUN_MAGLEV_NDAS_WORKFLOW:
    value: "false"
    options:
      - "true"
      - "false"
    description: "If set to true, images and maglev_launch_ndas_workflow will auto run without manual trigger."
  NDAS_WORKFLOW_ARGS:
    description: "Optional arguments passed to run_ndas_workflow.py for customization of maglev_run_ndas_workflow job. See [docs](https://docs.google.com/document/d/1VZ_99rSRXf1d4MEMIKiPyTHH6_AxY_o0eq6BFv5SLz0/edit?tab=t.v0mxg17hb24o#heading=h.ytv9ly7zvcld)"
  NDAS_WORKFLOW_CONFIG_ARG:
    description: "Optional, preset configs release_dataset, tiny_dataset (oneshot), medium_dataset (weekly), multi_gpu (nightly), hill_climbing_medium (nightly) can be selected to prefill many configs at once."
    value: ""
    options:
      - ""
      - "--ndas-workflow-config=lidarfree_sauron_15.yaml"
      - "--ndas-workflow-config=release_dataset.yaml"
      - "--ndas-workflow-config=tiny_dataset.yaml"
      - "--ndas-workflow-config=medium_dataset.yaml"
      - "--ndas-workflow-config=multi_gpu.yaml"
      - "--ndas-workflow-config=nrm.yaml"
      - "--ndas-workflow-config=profiling_workflow.yaml"
      - "--ndas-workflow-config=hill_climbing.yaml"
      - "--ndas-workflow-config=hill_climbing_medium.yaml"
  AUTO_RUN_MAGLEV_NDAS_WORKFLOW_LIDARFREE:
    description: "If set to true, images and maglev_launch_ndas_workflow_lidarfree will auto run without manual trigger."
    value: "false"
    options:
      - "true"
      - "false"


  AUTO_RUN_STANDALONE_MAGLEV_WF:
    description: "If set to true, standalone maglev workflow jobs will auto run. Does not depend on image build."
    value: "false"
    options:
      - "true"
      - "false"

stages:
  - build
  - deploy
  - system_tests
  - benchmark
  - security

workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    # Those rules follow this logic:
    # Phase 1: No open merge request, user pushes to a branch: --> Run branch pipeline
    # Phase 2: Open merge request: --> Do not run branch pipeline, but run merge result pipeline
    # Phase 3: Open merge request, user pushes to the branch: --> Re-run merge result pipeline
    # Phase 4: Branch is merged into protected branch: --> Run branch pipeline
    # Phase 5: RC tag is created: --> Run tag pipeline
    #
    # Additionally we do not allow auto-cancel of outdated pipelines on protected branches, we want to collect all
    # possible data points on these post-merge pipelines.
    - if: $CI_PIPELINE_SOURCE == "pipeline" # Run when triggered by a multi-project pipeline (e.g., from Sauron CI)
    - if: $CI_COMMIT_REF_PROTECTED == "true" # Run branch pipeline on protected branches (main or release)
      auto_cancel:
        on_new_commit: none
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Run merge request or merge result pipelines (if merge result pipelines are configured in gitlab)
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE != "web" # Do not run branch pipelines if merge request is open, but still allow web use
      when: never
    - if: $CI_COMMIT_BRANCH # Run branch pipelines for all branches when triggered by a branch push and no merge request is open
    - if: $CI_COMMIT_TAG =~ /^[0-9]{2}\.(0[1-9]|1[0-2])-rc[1-9][0-9]*$/ # Run on RC tags: YY.MM-rcN (25.08-rc1, 25.11-rc10, etc.)
      auto_cancel:
        on_new_commit: none

default:
  image:
    name: gitlab-master.nvidia.com:5005/nrs/nre:dev-v19
  tags:
    - type/docker
    - os/linux
    - arch/x86_64
    - gpu
    - 1_gpu
  interruptible: true
  artifacts:
    paths:
      # Created by bazelisk wrapper, won't exist if no bazelisk calls
      - bazel-telemetry/
    when: always
  before_script:
    - nvidia-smi -L
    - nvidia-smi

    # Fix git permission as we are running as a local user
    - git config --global --add safe.directory /builds/nrs/nre

    # Setup python-package / remote cache credentials
    - echo "machine $IT_ARTIFACTORY_MACHINE" >> ~/.netrc
    - echo "  login $IT_ARTIFACTORY_LOGIN" >> ~/.netrc
    - echo "  password $IT_ARTIFACTORY_PASSWORD" >> ~/.netrc

    - echo "machine $PYPACKAGE_MACHINE" >> ~/.netrc
    - echo "  login $PYPACKAGE_LOGIN" >> ~/.netrc
    - echo "  password $PYPACKAGE_PASSWORD" >> ~/.netrc
    - chmod 600 ~/.netrc

    # Setup docker-auth credentials config file by encoding local job's token into credentials
    - mkdir ~/.docker
    - CI_REGISTRY_ENCODED_PW=$(echo -n "$CI_REGISTRY_USER:$CI_JOB_TOKEN" | base64)
    - >
      echo "{ \"auths\": { \"${CI_REGISTRY}\": { \"auth\": \"${CI_REGISTRY_ENCODED_PW}\" }, \"${DEPLOY_REGISTRY}\": { \"auth\": \"${DEPLOY_REGISTRY_PASSWORD}\" } } }" > ~/.docker/config.json

    # Enable read-write access to remote-cache
    - echo "build --remote_cache=$REMOTE_CACHE_URL" >> .bazelrc.user
    - echo "build --remote_upload_local_results=true" >> .bazelrc.user

    # Setup persistent local disk-cache
    - echo "build --disk_cache=$CI_BUILDS_DIR/.ci-keep/bazel_cache" >> .bazelrc.user

    # Free up local disk space if filled up by cache
    - |
      # Check if $HOME disk usage is over 90%
      USAGE=$(df $HOME | awk 'NR==2 {print $5}' | sed 's/%//')
      if [ "$USAGE" -gt 90 ]; then
        echo "Running low on disk space, $USAGE% full. Cleaning disk-cache."
        sudo rm -rf $CI_BUILDS_DIR/.ci-keep
        docker image prune -a --force
        bazelisk clean --expunge
      fi
      df -h $HOME | awk 'NR==2 {print "Disk usage now: "$3" used of "$2", "$5" full"}'

    # Handle CI cache tag and remove / re-init cache if required
    - internal/scripts/ci/cache_tag.sh $CI_BUILDS_DIR/.ci-keep v8

    # Make Bazelisk use a persistent directory to cache Bazel binaries
    - export BAZELISK_HOME=$CI_BUILDS_DIR/.ci-keep/bazelisk

    # Set up writable and persistent directory for bazel tests
    - PERSISTENT_CACHE_DIR=$CI_BUILDS_DIR/.ci-keep/test_cache
    - mkdir -p $PERSISTENT_CACHE_DIR
    - echo "test --sandbox_writable_path=$PERSISTENT_CACHE_DIR" >> .bazelrc.user

    # Make use of local mypy cache
    - MYPY_CACHE_DIR=${PERSISTENT_CACHE_DIR}/mypy
    - echo "test --test_env=MYPY_CACHE_DIR=$MYPY_CACHE_DIR" >> .bazelrc.user

    # Set up cache / ngc api key for AH model downloads
    - ASSET_HARVESTER_CACHE_DIR=${PERSISTENT_CACHE_DIR}/asset_harvester
    - echo "test --test_env=ASSET_HARVESTER_CACHE_DIR=$ASSET_HARVESTER_CACHE_DIR" >> .bazelrc.user
    - echo "test --test_env=NGC_API_KEY=$NGC_API_KEY" >> .bazelrc.user

    # Set up torch home for torch model downloads
    - TORCH_HOME=${PERSISTENT_CACHE_DIR}/torch
    - echo "test --test_env=TORCH_HOME=$TORCH_HOME" >> .bazelrc.user

    # Set up triton home for triton model downloads
    - TRITON_CACHE_DIR=${PERSISTENT_CACHE_DIR}/triton
    - echo "test --test_env=TRITON_CACHE_DIR=$TRITON_CACHE_DIR" >> .bazelrc.user

    # Set up tinycudann cache for JIT compilation
    - TCNN_CACHE_DIR=${PERSISTENT_CACHE_DIR}/tinycudann
    - echo "test --test_env=TCNN_CACHE_DIR=$TCNN_CACHE_DIR" >> .bazelrc.user

    # Set up Huggingface caches
    - HF_HOME=${PERSISTENT_CACHE_DIR}/huggingface
    - echo "test --test_env=HF_HOME=$HF_HOME" >> .bazelrc.user

    # Use custom test timeouts in CI (longer than the defaults) to reduce the chance
    # of test timeouts
    - echo "test --config=ci_test_timeout" >> .bazelrc.user

    # Setup persistent outputUserRoot folder
    - echo ".ci-keep" >> .bazelignore
    - echo "startup --output_user_root $CI_BUILDS_DIR/.ci-keep/output" >> .bazelrc.user

    # Install Bazel and query its version
    - bazelisk version

    # Clean up telemetry folder if inherited from previous runs (e.g., downloaded artifacts)
    - rm -rf bazel-telemetry

    # Empty bazel-testlogs folder. This allows packaging test logs and test outputs from CI jobs without worrying
    # about which logs come from the current job. Bazel quickly refreshes already up-to-date files from the disk cache.
    - internal/scripts/ci/empty_testlogs.sh $(bazelisk info bazel-testlogs)

    # Determine GPU architecture of current CI machine
    # (only log result, not used to tweak build / test settings)
    - CUDA_ARCH=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader,nounits | head -1)
    - echo "Determined CUDA Architecture ${CUDA_ARCH}"

    # Log version string and extra info in case it's deemed dirty (unexpected in CI)
    - |
      VERSION_STRING=$(bazel/version/version_string.sh)
      echo "NuRec version string: $VERSION_STRING"
    - |
      if [[ "$VERSION_STRING" == *"+dirty" ]]; then
        echo "WARNING: Version string ends with '+dirty', indicating uncommitted changes"
        echo "Result of 'git diff-index HEAD' on the source tree:"
        git diff-index HEAD
      fi

# Template for jobs that run bazel test and need to expose logs as a job artifact
.bazel_test:
  after_script:
    # Copy contents of bazel-testlogs for packaging as an artifact. This is
    # necessary because the folder is a symlink that GitLab does not dereference
    # by itself.
    - |
      # Delete in case the artifact of a previous job was downloaded
      rm -rf testlogs
      mkdir -p testlogs
      if [ -d bazel-testlogs ]; then
        cp -rL --no-preserve=mode bazel-testlogs/* testlogs/
        # Filter-out empty folders to make the output easier to browse
        find testlogs -type d -empty -delete
      fi
  artifacts:
    paths:
      - bazel-telemetry/
      - testlogs/
    expose_as: "Bazel test logs and outputs"
    when: always

include:
  - local: .gitlab/ci/*.gitlab-ci.yml
