# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

sonar.projectKey=GPUSW_Pixels_NuRec_NuRec
sonar.projectName=nurec
sonar.host.url=https://sonar-sw.nvidia.com/


sonar.sources=nre,internal,libs
sonar.exclusions=**/BUILD.bazel,**/*.bzl,deps/**,bazel-*/**,docs/**,external/**,**/*.cu,**/*.cuh

sonar.python.version=3.11
sonar.cfamily.compile-commands=compile_commands.json

sonar.log.level=INFO
# Disable waiting for quality gate for now to avoid blocking CI pipelines because we have unresolved security hostspots and issues that will require some time to fix. We can re-enable this once we have addressed the issues.
# TODO: Re-enable waiting for quality gate once we have addressed the unresolved security hotspots and issues.
sonar.qualitygate.wait=false
