# SPDX-FileCopyrightText: Copyright (c) 2022-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_cuda//cuda:defs.bzl", "cuda_library")

package(default_visibility = ["//:core_package_group"])

cc_library(
    name = "ku_cc",
    hdrs = [
        "inc/ku/common_host.h",
    ],
    includes = ["inc"],
    deps = ["@nre_pip_deps//torch:torch_headers"],
)

cuda_library(
    name = "ku_cuda",
    hdrs = [
        "inc/ku/binary_search.cuh",
        "inc/ku/common.cuh",
        "inc/ku/helper_math.cuh",
        "inc/ku/morton.cuh",
    ],
    includes = ["inc"],
)
