# @package _global_

# This include the full model and loss configuration for Celsius dynamic model.
# Include this in your default list to apply.

defaults:
  - _static_full

  # Loss
  - override /loss/nrm@loss: celsius_dynamic

model:
  motion_module:
    enabled: true
    context_replace_start_global_step: 100000
    context_replace_end_global_step: 200000
  affine_module:
    # Start optimizing from start since we need init weight anyway
    optimization_start_global_step: 0
