# SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@mypy_integration//:mypy.bzl", "mypy_test")
load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@nre_pip_deps_internal//:requirements.bzl", pip_requirement_internal = "requirement")
load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "pylib_io",
    srcs = [
        "io.py",
    ],
    deps = [
        pip_requirement("numpy"),
    ],
)

py_binary(
    name = "mask_out_obj_pc",
    srcs = [
        "mask_out_obj_pc.py",
    ],
    main = "mask_out_obj_pc.py",
    deps = [
        ":pylib_io",
        pip_requirement("click"),
        pip_requirement("numpy"),
        pip_requirement("scipy"),
        pip_requirement("point_cloud_utils"),
    ],
)

mypy_test(
    name = "mask_out_obj_pc_mypy",
    timeout = "long",
    deps = [
        ":mask_out_obj_pc",
    ],
)

py_binary(
    name = "ncore_to_ngp",
    srcs = [
        "ncore_to_ngp.py",
    ],
    data = [
        "//configs",
    ],
    main = "ncore_to_ngp.py",
    deps = [
        ":pylib_io",
        pip_requirement("click"),
        pip_requirement("hydra-core"),
        pip_requirement("tqdm"),
        pip_requirement("numpy"),
        pip_requirement("omegaconf"),
        pip_requirement("pillow"),
        pip_requirement("nvidia-ncore"),
        "//nre/config:pylib",
        "//nre/datasets:pylib",
    ],
)

mypy_test(
    name = "ncore_to_ngp_mypy",
    timeout = "long",
    deps = [
        ":ncore_to_ngp",
    ],
)

py_binary(
    name = "export_config_diff",
    srcs = [
        "export_config_diff.py",
    ],
    data = [
        "//configs",
    ],
    main = "export_config_diff.py",
    deps = [
        pip_requirement("click"),
        pip_requirement("hydra-core"),
        "//nre/config:pylib",
        "//nre/datasets:pylib",
    ],
)

mypy_test(
    name = "export_config_diff_mypy",
    timeout = "long",
    deps = [
        ":export_config_diff",
    ],
)

py_binary(
    name = "ncore_aux_data_depth_normal",
    srcs = [
        "ncore_aux_data_depth_normal.py",
    ],
    main = "ncore_aux_data_depth_normal.py",
    visibility = [
        "//:aux_package_group",
    ],
    deps = [
        pip_requirement("pillow"),
        pip_requirement("tqdm"),
        pip_requirement("numpy"),
        "//nre/utils:pylib_ncore_utils",
    ],
)

py_binary(
    name = "render_point_cloud",
    srcs = [
        "render_point_cloud.py",
    ],
    main = "render_point_cloud.py",
    deps = [
        pip_requirement("click"),
        pip_requirement("imageio"),
        pip_requirement("imageio-ffmpeg"),
        pip_requirement("numpy"),
        pip_requirement("setuptools"),
        pip_requirement_internal("polyscope"),
        pip_requirement("point_cloud_utils"),
    ],
)

mypy_test(
    name = "render_point_cloud_mypy",
    timeout = "long",
    deps = [
        ":render_point_cloud",
    ],
)
