# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /apps/AV/NV/3dgut_dynamic.yaml
  - _alpasim_mixin

# overwrite some of the default parameters
loss: 
  lidar:
    lambda_: 0.03

checkpoint:
  every_n_train_steps: ${mul:${trainer.max_epochs},${dataset.n_samples_per_epoch}}
  artifact:
    nrend:
      enabled: false # TODO: nrend does not support dynamic 3dgut scenes yet

# This below section is changed to the original 3dgut config to gain some performance
# Note: this sacrifices some quality.

dataset:
  # note: was 2048 before, reduced in order to gain some performance
  n_train_sample_lidar_rays: 1024
  n_samples_per_epoch: 25000

model:
  layers:
    background:
      initialization:
        num_point_cloud_points: 800000
    dynamic_rigids:
      initialization:
        num_point_cloud_points: 3500
