# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - alpasim_3dgut


# overwrite some of the default parameters
dataset:
  samplers:
    batch_sampler:
      camera_pixel_sampler:
        subsample: 1
