# @package _global_
# Owner: Haithem Turki

defaults:
  - /apps/AV/_base_3dgut_static.yaml
  - _tesla_mixin.yaml

# Initialization defaults to lidar, and in the absence of lidar, the first camera sensor is used.
# Here we initialize with all camera sensors that we are using.
model:
  layers:
    background:
      initialization:
        camera_ids: ${dataset.camera_ids}
