# @package _global_
# Owner: Haithem Turki

dataset:
  n_train_sample_lidar_rays: 0
  valid_measurements_method: EGO_FRAMEMASKS
  valid_pixels_frame_mask_params:
    classes:
      - mask
      - sky_mask
  camera_ids:
    - camera_backup
    - camera_fisheye
    - camera_leftpillar
    - camera_leftrepeater
    - camera_main
    - camera_rightpillar
    - camera_rightrepeater
  lidar_ids: []
  n_val_image_subsample: 1
  samplers:
    batch_sampler:
      camera_pixel_sampler:
        subsample: 1
  camera_mask_overrides:
    camera_backup: /lustre/fsw/portfolios/nvr/users/hturki/Tesla-Batch2-masks/TCLP-2024-09-17-18-54-48-6BFAAD0B_2811.328806_backup_mask.png
    camera_fisheye: /lustre/fsw/portfolios/nvr/users/hturki/Tesla-Batch2-masks/TCLP-2024-09-17-18-54-48-6BFAAD0B_2811.328806_fisheye_mask.png
    camera_leftpillar: /lustre/fsw/portfolios/nvr/users/hturki/Tesla-Batch2-masks/TCLP-2024-09-17-18-54-48-6BFAAD0B_2811.328806_leftpillar_mask.png
    camera_leftrepeater: /lustre/fsw/portfolios/nvr/users/hturki/Tesla-Batch2-masks/TCLP-2024-09-17-18-54-48-6BFAAD0B_2811.328806_leftrepeater_mask.png
    camera_main: /lustre/fsw/portfolios/nvr/users/hturki/Tesla-Batch2-masks/TCLP-2024-09-17-18-54-48-6BFAAD0B_2811.328806_main_mask.png
    camera_rightpillar: /lustre/fsw/portfolios/nvr/users/hturki/Tesla-Batch2-masks/TCLP-2024-09-17-18-54-48-6BFAAD0B_2811.328806_rightpillar_mask.png
    camera_rightrepeater: /lustre/fsw/portfolios/nvr/users/hturki/Tesla-Batch2-masks/TCLP-2024-09-17-18-54-48-6BFAAD0B_2811.328806_rightrepeater_mask.png

loss:
  distance:
    lambda_: 0.003 # Slightly higher distance loss seems to improve NVS results
    min_distance: 0.1
    max_distance: 50
    mask_semantic_classes: [road]
    semantic_lambdas: [1.0]
