# SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@rules_python//python:defs.bzl", "py_library")

DEFAULT_VISIBILITY = [
    "//nre/nrm:__subpackages__",
]

filegroup(
    name = "py_files",
    srcs = glob(["**/*.py"]),
    visibility = [
    ],
)

py_library(
    name = "pylib",
    srcs = [
        "__init__.py",
        "datamodule.py",
        "nrm_base.py",
        "nrm_ncore.py",
        "registry.py",
        "samplers.py",
    ],
    visibility = DEFAULT_VISIBILITY,
    deps = [
        pip_requirement("nvidia-ncore"),
        pip_requirement("nvidia-ncore-internal"),
        pip_requirement("pandas"),
        pip_requirement("pytorch_lightning"),
        pip_requirement("universal-pathlib"),
        pip_requirement("s3fs"),
        pip_requirement("torch"),
        "//libs/vren:pylib",
        "//nre/datasets:pylib",
        "//nre/datasets:pylib_tracks",
        "//nre/nrm/config:pylib",
        "//nre/utils:pylib_files",
        "//nre/utils:pylib_misc",
        "//nre/utils:pylib_ncore_utils",
        "//nre/utils:pylib_types",
    ],
)
