defaults:
  - sh_gaussians

name: "rigid-gaussians"

optimize_track_albedo: false # whether to compute an affine albedo transformation at the track level
optimize_track_scale: false # whether to compute a track-level scale parameter
tracks:
  is_standalone: false

time_embed:
  name: individual-remap-time-input-embedding
  remap_min: 0
  remap_max: 1

is_static: false

track_albedo:
  start_global_step: 500
  optimizer:
    name: fused_adam
    args:
      lr: 1.0e-5
      eps: 1.e-15
      betas: [0.9, 0.99]
  scheduler:
    name: SequentialLR
    interval: step
    milestones:
      - ${...start_global_step}
      - ${add:${...start_global_step},${system.warmup_steps}}

    schedulers:
      - name: ConstantLR # skip until `start_global_step`
        args:
          factor: 0.0
          total_iters: ${.....start_global_step}
      - name: LinearLR # linear warm-up in the first system.warmup_steps steps
        interval: step
        args:
          start_factor: 0.01
          end_factor: 1.0
          total_iters: ${system.warmup_steps}
      - name: StepFunCosineAnnealingLR
        interval: step
        args:
          T_max: ${sub:${mul:${trainer.max_epochs},${dataset.n_samples_per_epoch}},${add:${.....start_global_step},${system.warmup_steps}}}
          min_factor: 0.0333
          update_every_n_steps: ${trainer.annealing_update_every_n_steps}

track_scale:
  start_global_step: 500
  optimizer:
    name: fused_adam
    args:
      lr: 1.0e-5
      eps: 1.e-15
      betas: [0.9, 0.99]
  scheduler:
    name: SequentialLR
    interval: step
    milestones:
      - ${...start_global_step}
      - ${add:${...start_global_step},${system.warmup_steps}}

    schedulers:
      - name: ConstantLR # skip until `start_global_step`
        args:
          factor: 0.0
          total_iters: ${.....start_global_step}
      - name: LinearLR # linear warm-up in the first system.warmup_steps steps
        interval: step
        args:
          start_factor: 0.01
          end_factor: 1.0
          total_iters: ${system.warmup_steps}
      - name: StepFunCosineAnnealingLR
        interval: step
        args:
          T_max: ${sub:${mul:${trainer.max_epochs},${dataset.n_samples_per_epoch}},${add:${.....start_global_step},${system.warmup_steps}}}
          min_factor: 0.0333
          update_every_n_steps: ${trainer.annealing_update_every_n_steps}
