# @package _global_
# Owner: Haithem Turki

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /experimental/3dgut/3dgut_lidar_dynamic.yaml
  - override /model/post_processing@model.post_processing.b: null
  - override /model/post_processing@model.post_processing.c: null

dataset:
  path: /lustre/fsw/portfolios/nvr/users/hturki/data/c6ba_multi_cam/c6ba8e54-ba7b-11eb-98ad-00044baf74dc_1621633383349946_1621633411050024.json
  duration_sec: 12.0
  cuboid_tracks_params:
    track_min_speed_ms: 0 # The car at the very beginning of the clip gets registered as background otherwise
  train_camera_ids:
    - camera_front_wide_120fov
    - camera_cross_right_120fov
    - camera_cross_left_120fov

system:
  test:
    val_render_selected_nodes:
      background_only:
        - background
      rigids:
        - dynamic_rigids
      deformables:
        - dynamic_deformables

trainer:
  num_sanity_val_steps: -1
