# SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//bazel/pytest:defs.bzl", "pytest_test")

# ----------------------------------------------------------------------------------

filegroup(
    name = "py_files",
    srcs = glob(["**/*.py"]),
    visibility = [
    ],
)

################################################################
# Deps list
################################################################

NCORE_AUX_DATA_DEPS = [
    pip_requirement("torch"),
    pip_requirement("nvidia-ncore"),
    pip_requirement("nvidia-ncore-internal"),
    pip_requirement("click"),
    pip_requirement("tqdm"),
    pip_requirement("numpy"),
    pip_requirement("zarr"),
    pip_requirement("torchvision"),
    pip_requirement("dataclasses_json"),
    pip_requirement("depthanythingv2"),
    pip_requirement("point-cloud-utils"),
    pip_requirement("universal-pathlib"),
    pip_requirement("s3fs"),
    pip_requirement("setuptools"),
    pip_requirement("pillow"),
    ":pylib_estimators_aux",
    ":pylib_utils_aux",
    "//nre/utils:pylib_cli",
    "//nre/utils:pylib_files",
    "//nre/utils:pylib_ncore_utils",
    "//nre/utils:pylib_types",
    "//nre/utils/debug:pylib",
]

NCORE_AUX_DATA_DATA = [
    "//:notices_file",
]

################################################################
# Python libs
################################################################

py_library(
    name = "pylib_estimators_aux",
    srcs = [
        "estimators.py",
    ],
    data = [
        "@pretrained_models_repo//auto_egomask:model_egomask",
        "@pretrained_models_repo//depth:model_depth",
        "@pretrained_models_repo//depth:model_depth_metric",
        "@pretrained_models_repo//segmentation:model_mask2former",
        "@trt_pretrained_models_repo//segmentation:model_mask2former",
    ],
    deps = [
        pip_requirement("pillow"),
        pip_requirement("pycuda"),
        pip_requirement("tensorrt-cu12"),
        pip_requirement("tensorrt-cu12-bindings"),
        pip_requirement("tensorrt-cu12-libs"),
        pip_requirement("sam2"),
        pip_requirement("scipy"),
        "//libs/vren:pylib",
        "//nre/utils:pylib_geometry",
        "@mmseg_repo//:pylib_aux",
        "@rules_python//python/runfiles",
    ],
)

py_library(
    name = "pylib_utils_aux",
    srcs = [
        "utils.py",
    ],
    deps = [
        pip_requirement("matplotlib"),
        pip_requirement("numpy"),
        pip_requirement("scipy"),
    ],
)

py_library(
    name = "pylib",
    srcs = [
        "ncore_aux_data.py",
    ],
    visibility = [
        "//apps:__pkg__",
    ],
    deps = NCORE_AUX_DATA_DEPS,
)

################################################################
# PyBinary rules
################################################################

py_binary(
    name = "ncore_aux_data",
    srcs = [
        "ncore_aux_data.py",
    ],
    data = NCORE_AUX_DATA_DATA,
    main = "ncore_aux_data.py",
    visibility = [
        # Add visibility for //internal/scripts/ci:python_absolute_path_check
    ],
    deps = NCORE_AUX_DATA_DEPS,
)

pytest_test(
    name = "ncore_aux_data_test",
    srcs = ["ncore_aux_data_test.py"],
    deps = [":pylib"],
)

pytest_test(
    name = "aux_gen_test",
    timeout = "long",
    srcs = [
        "aux_gen_test.py",
    ],
    data = [
        "@test_data_ncore//:ncore_1sec",
    ],
    deps = [
        ":ncore_aux_data",
        pip_requirement("pytest-grpc"),
        pip_requirement("grpcio"),  # required by pytest-grpc
        pip_requirement("click"),
        "@rules_python//python/runfiles",
    ],
)

pytest_test(
    name = "trt_torch_comparison_test",
    timeout = "long",
    srcs = [
        "trt_torch_comparison_test.py",
    ],
    data = [
        "@pretrained_models_repo//segmentation:model_mask2former",
        "@test_data_ncore//:ncore_1sec",
        "@trt_pretrained_models_repo//segmentation:model_mask2former",
    ],
    tags = [
        "manual",
        "no-remote-cache",
    ],
    deps = [
        ":ncore_aux_data",
        pip_requirement("pytest-grpc"),
        pip_requirement("grpcio"),  # required by pytest-grpc
        pip_requirement("click"),
    ],
)
