# @package _global_

checkpoint:
  artifact:
    enabled: true
    checkpoint:
      enabled: true
    nrend:
      enabled: false
      use_legacy_model_dict: false # Export the legacy model dictionary (for OV rendering support)
    parsed_config:
      enabled: true
    rig_trajectories:
      enabled: true
    sequence_tracks:
      enabled: true
