defaults:
  - 3dgrut_nrend

name: 3dgrt-optix-nrend

pipeline:
  # pipelines are 
  # reference : reference implementation supporting all primitives (except sphere) and K-Buffer of up to 16
  # reference_instance : instance primitive specific implementation (with opacity encoded in instance id), with K-Buffer up to 10
  # rejection_sampling : rejection sampling implementation
  type: reference # pipeline used during inference by default
  fwd_type: ${model.renderer.pipeline.type} # forward pipeline used during optimization
  bwd_type: ${model.renderer.pipeline.fwd_type} # backward pipeline
  
  k_buffer_size: 16

primitives:
  type: transformed_aabb # in [transformed_aabb, tetrahedra, diamond, octahedron, icosahedron, aabb, trisurfel, rhombus, sphere]
  density_scale: true # if true clamp the primitive scale by the opacity
