defaults:
  - 3dgrut_nrend

name: 3dgut-nrend

global_z_order: false
per_ray_features: false

use_gsplat_for_camera_rendering: false

projection:
  n_rolling_shutter_iterations: 5
  ut_dim: 3
  ut_alpha: 1.0
  ut_beta: 2.0
  ut_kappa: 0.0
  ut_require_all_sigma_points: true
  image_margin_factor: 0.1
  min_projected_ray_radius: 0.5477225575051661 # gsplat default of √0.3

culling:
  rect_bounding: true
  tight_opacity_bounding: true
  tile_based: true
  enable_ray_based_culling: true

render:
  mode: kbuffer # in [kbuffer, splat]
  k_buffer_size: 0
  enable_warp_atomic_optim: true

tiling:
  camera:
    tile_width: 16
    tile_height: 16
  lidar:
    tile_size_elevation: 16
    tile_size_azimuth: 16
    n_bins_elevation: 16  # number of tiles in the elevation direction to use for LiDAR rendering
    resolution_elevation: 1600
    densification_factor_azimuth: 8
