# @package _global_

# This include the full model and loss configuration for Kelvin static model.
# Include this in your default list to apply.

defaults:
  - /nrm/nrm_base

  # Loss
  - /loss/nrm@loss: kelvin_static

system:
  max_epochs: 20
  # fp16 requires grad scaling which would waste some steps
  # and introduce some instability
  precision: bf16

  # Invariant to batch size, must be >= 1.
  warmup_steps: 100
  optimizer:
    name: fused_adam
    args:
      lr: 1e-4
      eps: 1.e-15
      betas: [0.9, 0.99]

  scheduler:
    name: CosineWithWarmupPBScheduler
    interval: step
    args:
      warmup_factor: 0.01
      warmup_steps: ${system.warmup_steps}
      cosine_factor: 0.0333
      cosine_factor_progress: 1.0
