# SPDX-FileCopyrightText: Copyright (c) 2022-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@rules_cc//cc:defs.bzl", "cc_binary")
load("@rules_python//python:defs.bzl", "py_library")
load("//deps/numpyeigen:npe_add_module.bzl", "npe_codegen_function", "npe_codegen_module")

DEFAULT_VISIBILITY = ["//:core_package_group"]

package(default_visibility = DEFAULT_VISIBILITY)

filegroup(
    name = "py_files",
    srcs = glob(["*.py"]),
)

npe_codegen_function(
    name = "ray_utils_codegen_function",
    src = ":ray_utils.cpp",
    out = ":ray_utils_function.cpp",
)

npe_codegen_module(
    name = "ray_utils_codegen_module",
    src = ":ray_utils.cpp",
    out = ":ray_utils_module.cpp",
    module = "libray_utils_cc",
)

cc_binary(
    name = "ray_utils_cc",
    srcs = [
        ":ray_utils_function.cpp",
        ":ray_utils_module.cpp",
    ],
    linkshared = True,
    deps = [
        "@numpyeigen//:npe",
    ],
)

py_library(
    name = "pylib_cc",
    srcs = [
        "__init__.py",
        "interface.py",
    ],
    data = [
        ":ray_utils_cc",
    ],
    visibility = DEFAULT_VISIBILITY + [
        "//bazel/docs:__pkg__",
    ],
)
