# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

"""Repository rule to gather GPU information using nvidia-smi.

This rule runs at repository fetch time and creates a .bzl file with GPU info.
The value is cached until Bazel re-fetches the repository (e.g., after cache
invalidation or rule changes).

Auto-detection will be skipped if set FORCE_GPU_COUNT is set in the environment,
ex. through .bazelrc.user:
    common --repo_env=FORCE_GPU_COUNT=2
"""

def _gpu_info_impl(repository_ctx):
    """Gather GPU information using nvidia-smi, unless a value comes from the env."""
    forced_count = repository_ctx.getenv("FORCE_GPU_COUNT")
    if forced_count != None:
        gpu_count = int(forced_count)
    else:
        # Auto-detect using nvidia-smi
        result = repository_ctx.execute(
            ["nvidia-smi", "--query-gpu=index", "--format=csv,noheader"],
            quiet = True,
            timeout = 10,
        )

        if result.return_code == 0 and result.stdout.strip():
            gpu_count = len(result.stdout.strip().split("\n"))
        else:
            # nvidia-smi not available or no GPUs detected
            gpu_count = 0

    # Create required BUILD file with exports
    repository_ctx.file("BUILD.bazel", 'exports_files(["defs.bzl"])\n')

    # Create .bzl file with the detected value
    repository_ctx.file(
        "defs.bzl",
        """# Auto-generated by gpu_info repository rule

GPU_COUNT = {gpu_count}
""".format(gpu_count = gpu_count),
    )

gpu_info = repository_rule(
    implementation = _gpu_info_impl,
    local = True,
    configure = True,
    doc = "Gathers GPU information (currently, count only) using nvidia-smi.",
)
