# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@rules_python//python:defs.bzl", "py_library")

DEFAULT_VISIBILITY = [
    "//nre/nrm:__subpackages__",
]

filegroup(
    name = "py_files",
    srcs = glob(["**/*.py"]),
    visibility = [
    ],
)

py_library(
    name = "pylib",
    srcs = [
        "__init__.py",
        "base.py",
        "gaussians_nrm.py",
        "test_data_system.py",
    ],
    visibility = DEFAULT_VISIBILITY,
    deps = [
        "//libs/losses:pylib",
        "//nre/config:pylib",
        "//nre/datasets:pylib_tracks",
        "//nre/nrm/datasets:pylib",
        "//nre/nrm/models:pylib",
        "//nre/nrm/predict:pylib",
        "//nre/nrm/primitives:pylib",
        "//nre/nrm/utils:pylib",
        "//nre/nrm/utils:pylib_trajectory",
        "//nre/utils:pylib",
        "//nre/utils:pylib_custom_metrics",
        "//nre/utils:pylib_geometry",
        "//nre/utils:pylib_misc",
        "//nre/utils:pylib_optim",
        "//nre/utils:pylib_types",
        pip_requirement("torch"),
        pip_requirement("pytorch-lightning"),
        pip_requirement("numpy"),
        pip_requirement("einops"),
        pip_requirement("nvidia-ncore"),
        pip_requirement("torchmetrics"),
    ],
)
