defaults:
  - _self_

num_workers: 1

name: ???
exec_mode: docker # Only docker available for Maglev and [bazel, docker] for ORD

docker:
  image: nvcr.io/nvidian/ct-toronto-ai/nre-run-dev # <registry><image-path>:optional[<tag>]
  build_push: true # by default we build and push a new image, but you can disable that and use an existing image

wandb:
  api_key: null
  entity: nvidia-toronto
  project: NRE
  tags: []
  # By default limit number of maximum jobs per agent to 1 if using wandb sweep.
  # This ensures that no new jobs will be run towards the end of cluster time limit (e.g. 4 hours for SLURM).
  max_job_per_agent: 1
