; Copyright (c) 2023-2026 NVIDIA CORPORATION.  All rights reserved.

[mypy]
show_error_codes = True

# might be nice to enable, however, there are some ignores required to make pylance happy also
warn_unused_ignores = False

# disable method-assign due to use of MethodType to monkey-patch methods
disable_error_code = method-assign

verbosity = 0

# These packages don't provide type-stubs - the ones that provide stubs should be listed in `bazel/typing/BUILD.bazel`
[mypy-parameterized.*]
ignore_missing_imports = True

[mypy-torchvision.*]
ignore_missing_imports = True

[mypy-zarr.*]
ignore_missing_imports = True

[mypy-numcodecs.*]
ignore_missing_imports = True

[mypy-cv2.*]
ignore_missing_imports = True

[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-flow_vis.*]
ignore_missing_imports = True

[mypy-einops.*]
ignore_missing_imports = True

[mypy-apex.*]
ignore_missing_imports = True

[mypy-torch_scatter.*]
ignore_missing_imports = True

[mypy-polyscope.*]
ignore_missing_imports = True

[mypy-diffusers.*]
ignore_missing_imports = True

[mypy-tinycudann.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-tqdm.*]
ignore_missing_imports = True

[mypy-mcubes.*]
ignore_missing_imports = True

[mypy-mmengine.*]
ignore_missing_imports = True

[mypy-trimesh.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-maglev.workflows.*]
ignore_missing_imports = True

[mypy-debugpy.*]
ignore_missing_imports = True

[mypy-msgpack.*]
ignore_missing_imports = True

[mypy-pxr.*]
ignore_missing_imports = True

[mypy-poisson_recon.*]
ignore_missing_imports = True

[mypy-point_cloud_utils.*]
ignore_missing_imports = True

# Consider adding this one to mypy local requirements
[mypy-maglev.ray_utils.*]
ignore_missing_imports = True

[mypy-nvdiffrast.*]
ignore_missing_imports = True

[mypy-diffshadow.*]
ignore_missing_imports = True

[mypy-lietorch.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-click_default_group.*]
ignore_missing_imports = True

# wandb has type-annotations, but skipping due to mypy caching issues
[mypy-wandb.*]
ignore_missing_imports = True

[mypy-grpc.*]
ignore_missing_imports = True

[mypy-nvidia.*]
ignore_missing_imports = True

[mypy-pycolmap_reader.*]
ignore_missing_imports = True

[mypy-fused_ssim.*]
ignore_missing_imports = True

[mypy-ncore_internal.impl.common.nvidia_utils.*]
ignore_missing_imports = True

[mypy-simple_lama_inpainting.*]
ignore_missing_imports = True

[mypy-OpenEXR.*]
ignore_missing_imports = True

[mypy-aiofiles.*]
ignore_missing_imports = True

[mypy-numba.*]
ignore_missing_imports = True

[mypy-google.protobuf.*]
ignore_missing_imports = True

[mypy-PySide6.*]
ignore_missing_imports = True

[mypy-sam2.*]
ignore_missing_imports = True

[mypy-slangtorch.*]
ignore_missing_imports = True

[mypy-python.runfiles.*]
ignore_missing_imports = True

[mypy-pyrallis.*]
ignore_missing_imports = True

[mypy-asset_harvester.*]
ignore_missing_imports = True

[mypy-transformers.*]
ignore_missing_imports = True

[mypy-kiui.*]
ignore_missing_imports = True

[mypy-dataverse.*]
ignore_missing_imports = True

[mypy-mamba_ssm.ops.triton.*]
ignore_missing_imports = True

[mypy-safetensors.*]
ignore_missing_imports = True

[mypy-simplejpeg.*]
ignore_missing_imports = True

[mypy-transformer_engine.*]
ignore_missing_imports = True

[mypy-transformer_engine.pytorch.*]
ignore_missing_imports = True

[mypy-coverage.*]
ignore_missing_imports = True

[mypy-pytest_shard.*]
ignore_missing_imports = True

[mypy-cuml.*]
ignore_missing_imports = True

[mypy-ray.*]
ignore_missing_imports = True

[mypy-libs.tracy_utils.*]
ignore_missing_imports = True
