script: run.py
obfuscation_modules:
  - mod: nre
    mod_dir: nre
  - mod: internal.scripts
    mod_dir: internal/scripts
  - mod: libs
    mod_dir: libs
build_dir: internal/scripts/pycena
template_dir: internal/scripts/pycena/templates
dump_ast: False
debug: False
skip_script: True
script_prefix: run
python_version: "3.11"
python_build_root: ../rules_python++python+python_3_11_x86_64-unknown-linux-gnu
python_run_root: ../rules_python++python+python_3_11_x86_64-unknown-linux-gnu
priority_pass_modules_regex:
  - '.*\.registry'
