# @package _global_

dataset:
  camera_ids: 
    - camera_cross_right_120fov
    - camera_cross_left_120fov
    - camera_front_wide_120fov
    - camera_front_tele_30fov
    - camera_front_left_shifted_120fov
    - camera_front_right_shifted_120fov
  train_camera_ids:
    - camera_cross_right_120fov
    - camera_cross_left_120fov
    - camera_front_wide_120fov
    - camera_front_tele_30fov
  lidar_ids:
    - lidar_gt_top_p128_v4p5
