# @package _global_

defaults:
  - override /model/post_processing@model.post_processing.b: null # bilarf per camera, should be disabled in single-cam session

dataset:
  camera_ids:
  - camera_front_wide_120fov
  lidar_ids:
  - lidar_gt_top_p128
