# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@rules_python//python:defs.bzl", "py_library")

DEFAULT_VISIBILITY = ["//:core_package_group"]

package(default_visibility = DEFAULT_VISIBILITY)

filegroup(
    name = "py_files",
    srcs = [
        "__init__.py",
    ],
)

py_library(
    name = "pylib",
    srcs = [
        "__init__.py",
    ],
    visibility = DEFAULT_VISIBILITY + [
        "//bazel/docs:__pkg__",
    ],
    deps = [
        "//libs/losses/functional:pylib",
        "//libs/losses/kernel:pylib_cc",
        "//libs/losses/models:pylib",
        "//libs/losses/orchestration:pylib",
    ],
)
