defaults:
  - base

name: gaussians-system
max_split_size_mb: null # Read docs before using: https://pytorch.org/docs/stable/notes/cuda.html#environment-variables
save_logger: true
record_timings:
  train_interval: 1000
  val_interval: 1000
record_quality_metrics:
  psnr_interval: 100

test:
  nrend:
    enabled: false
    rendered_model_json_path: null # path to a json file to override the default model config
    renderer_hint : 0 # [0 : default (used for training), 1 : fastest, 2 : fast, 3 : quality, 4 : highest quality, 5 : fast quality, 6 : quality fast]
    renderer_settings_json_path: null # path to a json file toverride the default renderer settings
    log_level: 1 # loging level of the nrend : [0=FATAL,1=ERROR,2=WARNING,3=INFO,4=DEBUG]
    profiling_frequency : 0.
  save_results: true
  save_inputs: false
  save_videos: true
  save_stats: false
  save_extra_signals: false
  separate_val_dir_per_step: false
  use_camera_name_dirs: false
  frame_naming: batch-index
  video_fps: 30
  track_ply:
    overrides: {}
    transform: [[1, 0, 0, 0], [0, 0, -1, 0], [0, 1, 0, 0], [0, 0, 0, 1]]
  track_orbit:
    track_ids: []
    distance: 5
    n_frames: 45
    render_width: 512
    render_height: 256
    video_fps: 5
  track_rotation:
    track_ids: []
    angle_per_frame: 0
    angle_offsets: []
  # Background gaussians in these tracks will be removed
  background_removal:
    track_ids: []
    track_shift_m: [0, 0, 0]
    track_padding_m: [0, 0, 0]

  # Generate additional renderings using only the specified layers
  # Example:
  # val_render_selected_nodes:
  #   background_only:
  #     - background
  #   no_deformables:
  #     - background
  #     - dynamic_rigids
  val_render_selected_nodes: {}
  metrics:
    cpsnr:
      enabled: true
      classes: null  # If specified, only compute cpsnr for these classes, else for all classes
    ssim:
      enabled: false
    lpips:
      enabled: false
  lidar:
    raydrop_threshold: 0.5    # threshold for filtering based on raydrop probability, [0-1], used in point cloud post-processing during inference. 
    ROI:                # If definesd, region of interest for evaluation, indicating a circular ROI with minimum and maximum distances (in meters).
      min_m: null
      max_m: null
    save_renders:
      enabled: false
      root: [0, 0, 0] # camera position (in lidar sensor coordinates)
      look_dir: [1, 0, 0] # camera look direction (in lidar sensor coordinates)
      up_dir: [0, 0, 1] # camera up direction (in lidar sensor coordinates)
      radius: 0.04 # point cloud radius
    save_filtered_pc:
      enabled: false
      filter_threshold: 0.02 # The higher the threshold, the fewer floating-point numbers are filtered out.

warmup_steps: 0
optimizers:
  - name: fused_adam
    args:
      lr: 0.01
      eps: 1.e-15
      betas: [0.9, 0.99]
    params:
      background:
        args:
          lr: 0.001 # Lower LR found to be helpful in 3DGRT need experimentation
    scheduler:
      name: StepFunCosineAnnealingLR
      interval: step
      args:
        T_max: ${mul:${trainer.max_epochs},${dataset.n_samples_per_epoch}}
        min_factor: 0.0333
        update_every_n_steps: ${trainer.annealing_update_every_n_steps}
