# inherits from gaussians.yaml
defaults:
  - gaussians

name: nrend-test-gaussians-system

test:
  nrend:
    create_test_case: False
    create_test_case_update: True
    overlay_render_time: False

