# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@mypy_integration//:mypy.bzl", "mypy_test")
load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")

py_binary(
    name = "ncore_vis",
    srcs = [
        "data_utils.py",
        "lazy_loader.py",
        "loader.py",
        "ncore_vis.py",
        "viewer.py",
    ],
    main = "ncore_vis.py",
    deps = [
        "//nre/datamodules:pylib",
        "//nre/utils:pylib",
        "//nre/utils:pylib_ncore_utils",
        "//nre/utils/debug:pylib",
        pip_requirement("click"),
        pip_requirement("viser"),
        pip_requirement("numpy"),
        pip_requirement("nvidia-ncore"),
        pip_requirement("nvidia-ncore-internal"),
        pip_requirement("tqdm"),
        pip_requirement("trimesh"),
        pip_requirement("opencv-python"),
        pip_requirement("pyliblzfse"),
    ],
)

mypy_test(
    name = "ncore_vis_mypy",
    timeout = "long",
    deps = [
        ":ncore_vis",
    ],
)
