# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@mypy_integration//:mypy.bzl", "mypy_test")
load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")

package(default_visibility = ["//visibility:private"])

# Regular py_binary for the scheduler
py_binary(
    name = "scheduler",
    srcs = ["scheduler.py"],
    main = "scheduler.py",
    visibility = ["//visibility:public"],
    deps = [
        pip_requirement("click"),
        pip_requirement("ray"),
        pip_requirement("pyyaml"),
    ],
)

mypy_test(
    name = "run_scheduler_mypy",
    timeout = "long",
    deps = [
        ":scheduler",
    ],
)

# py_binary for the ray worker
py_binary(
    name = "worker",
    srcs = ["worker.py"],
    main = "worker.py",
    visibility = ["//visibility:public"],
    deps = [
        pip_requirement("ray"),
    ],
)
