# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@mypy_integration//:mypy.bzl", "mypy_test")
load("@rules_python//python:defs.bzl", "py_library")

py_binary(
    name = "run_benchmark",
    srcs = [
        "run_benchmark.py",
    ],
    data = [
        "//configs",
        "//internal/workflows/cluster_toolbox/cluster_configs",
        "//internal/workflows/cluster_toolbox/job_templates",
        "//internal/workflows/cluster_toolbox/wandb_sweep_configs",
        "@maglev_cli//file:maglev",
    ],
    main = "run_benchmark.py",
    deps = [
        "pylib",
        "//internal/workflows/cluster_toolbox:pylib",
    ],
)

py_library(
    name = "pylib",
    srcs = [
        "__init__.py",
        "benchmark_toolbox.py",
        "run_benchmark.py",
    ],
)

mypy_test(
    name = "run_benchmark_mypy",
    timeout = "long",
    deps = [
        ":run_benchmark",
    ],
)
