# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

DEFAULT_VISIBILITY = ["//:core_package_group"]

package(default_visibility = DEFAULT_VISIBILITY)

# This target is added as a layer in regular (non-obfuscated) images and thus requires visibility to root package
filegroup(
    name = "architecture_docs",
    srcs = [
        "modules-geometry.md",
        "modules-losses.md",
        "modules-scene.md",
    ] + [
        "//docs/architecture/examples",
    ],
    visibility = DEFAULT_VISIBILITY + [
        "//:__pkg__",
    ],
)
