# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_python//python:defs.bzl", "py_library")
load("@rules_python//python:packaging.bzl", "py_package", "py_wheel")
load("//bazel/pytest:defs.bzl", "pytest_test")
load(":defs.bzl", "nrend_libs", "obfuscate_jit_headers")

DEFAULT_VISIBILITY = [
    "//:asset_harvester_package_group",
    "//:core_package_group",
]

package(default_visibility = DEFAULT_VISIBILITY)

filegroup(
    name = "py_files",
    srcs = [
        "__init__.py",
        "renderer.py",
    ],
)

# define the single NRend library using all TinyCUDA NN dependencies
nrend_libs(architectures = [
    "80",
    "86",
    "89",
    "90",
    "100",
    "120",
])

NREND_JIT_HEADERS = glob(["include/nrend/**/*"]) + glob([
    "include/neural-graphics-primitives/**/*",
])

# register obfuscated header build targets
obfuscate_jit_headers(headers = NREND_JIT_HEADERS)

cc_library(
    name = "cclib",
    data = [
        ":nrend_cc",
        "@optix_dev//:optix_jit_headers",
    ] + select({
        # skip obfuscation of JIT headers if explicitly requested by user
        "@//bazel/conditions:skip_nrend_obfuscation": NREND_JIT_HEADERS,
        # use obfuscated JIT headers by default
        "//conditions:default": ["obfuscated/%s" % x for x in NREND_JIT_HEADERS],
    }),
)

py_library(
    name = "pylib",
    srcs = [
        ":py_files",
    ],
    data = [
        "@optix_dev//:optix_headers",
    ],
    visibility = DEFAULT_VISIBILITY + [
        "//bazel/docs:__pkg__",
    ],
    deps = [
        ":cclib",
        "//libs/vren:pylib",  # camera parametrization
        "//nre/utils:pylib",
        pip_requirement("numpy"),
        pip_requirement("torch"),
        pip_requirement("nvidia-ncore"),
        pip_requirement("msgpack"),
        pip_requirement("tinycudann"),
        "@rules_python//python/runfiles",
    ],
)

py_package(
    name = "pkg",
    packages = ["libs/nrend"],
    deps = [":pylib"],
)

py_wheel(
    name = "wheel",
    distribution = "nrend",
    platform = "linux_x86_64",
    python_tag = "py311",
    requires = [
        "tinycudann==1.8.4+gitc2de4fapt2.7.0cu128sm75to120",
        "torch",
        "numpy",
        "ncore",
        "msgpack",
        "vren>=0.1.4",
        # slangtorch provides the slang runtime libraries (libslang-compiler.so, libslang-rt.so) and
        # slangc compiler needed by NRend for JIT compilation of Slang kernels
        "slangtorch>=1.3.18",
    ],
    version = "0.1.4",
    deps = [":pkg"],
)

