name: null

# Path to directory containing  NGP .json transformation files
# files to load, or the path to a single NGP .json to load
path: ???

downsample: 1.0
n_samples_per_epoch: 30000
n_train_sample_camera_rays: 8192
n_val_image_subsample: 4
aux_data: true
train_sample_full_image: false # If set, each batch will contain rays from a randomly selected full image

n_train_sequential_image_subsample: 4
