# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//bazel/pytest:defs.bzl", "pytest_test")

package(default_visibility = ["//:core_package_group"])

filegroup(
    name = "py_files",
    srcs = glob(["**/*.py"]),
    visibility = [
    ],
)

py_library(
    name = "pylib_test_utils",
    srcs = [
        "test_utils.py",
    ],
    deps = [
        "//nre/utils:pylib_trainer",
    ],
)

py_library(
    name = "pylib",
    srcs = [
        "__init__.py",
        "base.py",
        "gsplat.py",
        "mcmc.py",
        "selected_gaussian_nodes.py",
    ],
    deps = [
        pip_requirement("nvidia-ncore"),
        pip_requirement("numpy"),
        pip_requirement("torch"),
        pip_requirement("omegaconf"),
        pip_requirement("tqdm"),
        "//libs/slang_gaussians:pylib",
        "//nre/datasets:pylib",
        "//nre/models/base:pylib",
        "//nre/models/gaussians:pylib",
        "//nre/utils:pylib_optim",
        "//nre/utils:pylib_types",
    ],
)

pytest_test(
    name = "base_test",
    srcs = ["base_test.py"],
    deps = [
        ":pylib",
        ":pylib_test_utils",
    ],
)

pytest_test(
    name = "gsplat_test",
    srcs = ["gsplat_test.py"],
    deps = [
        ":pylib",
        ":pylib_test_utils",
    ],
)

pytest_test(
    name = "mcmc_test",
    srcs = ["mcmc_test.py"],
    deps = [
        ":pylib",
        ":pylib_test_utils",
    ],
)

pytest_test(
    name = "selected_gaussian_nodes_tests",
    srcs = ["selected_gaussian_nodes_tests.py"],
    deps = [
        ":pylib",
        ":pylib_test_utils",
    ],
)
