defaults:
  - _kelvin_dav3

encoder:
  depth: 12
  n_heads: 12
  embed_dim: 1536  # 768 * 2
  take_block_indices: [5, 7, 9, 11]
  aa_start_block_idx: 4
  ffn_type: "mlp"

decoder:
  dpt_dim: 128
  dpt_reassemble_hidden_dims: [96, 192, 384, 768]

sky:
  embed_dim: 384

init_weights_paths:
  dav3: s3@pdx-team-ncore://nrm-training-data/init-ckpt/dav3/base.safetensors
