#!/usr/bin/env bash

# Copyright (c) 2023 NVIDIA CORPORATION.  All rights reserved.

# This script prints public version info, given the input file bazel-out/stable-status.txt generated by Bazel
# using workspace_status.sh as --workspace_status_command.
# (see https://bazel.build/docs/user-manual#workspace-status)
#
# The output is a list of key-value pairs in YAML format, for example:
#
# GIT_COMMIT_DATE: 2024-02-27T12:33:04+01:00
# GIT_COMMIT_SHA: 0590e85906829fe1d2c851408894c8efc70e0194
# VERSION_STRING: 0.1.35-0590e859+dirty
#
# You can extract the value for a key, e.g. VERSION_STRING, in one of the following ways in Bash:
# bash version_file_yaml.sh | sed -nE "s/(VERSION_STRING:)(\s*)(.+)/\3/ p"
# bash version_file_yaml.sh | grep "^VERSION_STRING: " | cut -d ' ' -f2
#
# GIT_COMMIT_DATE is in ISO 8601 format as reported by: git show -s --format=%cI

set -eo pipefail # Exit immediately if any command fails.

INPUT_FILE=bazel-out/stable-status.txt
sed 's/^STABLE_//' ${INPUT_FILE} | sed -nE 's/(^VERSION_STRING|^GIT_COMMIT_SHA|^GIT_COMMIT_DATE)(.+)/\1:\2/ p'
