name: free-pose-calib
start_global_step: 250                     # freeze all estimated parameters until this global optimization step
skip_first_pose_delta: true                # if enabled, make sure to fix the initial pose globally to maintain a potential geo-spatial map-alignment
enable_torch_compile: true                 # enable torch.compile for calibration

lidar:
  enabled: true
camera:
  enabled: true

optimizer:
  name: fused_adam
  args:
    lr: 0.0001
    eps: 1.e-15
    betas: [0.9, 0.99]
    weight_decay: 0.000001
scheduler:
  name: SequentialLR
  interval: step
  milestones:
    - ${...start_global_step}
    - ${add:${...start_global_step},${system.warmup_steps}}

  schedulers:
    - name: ConstantLR # skip until `start_global_step`
      args:
        factor: 0.0
        total_iters: ${.....start_global_step}
    - name: LinearLR # linear warm-up in the first system.warmup_steps steps
      interval: step
      args:
        start_factor: 0.01
        end_factor: 1.0
        total_iters: ${system.warmup_steps}
    ## Slowly attenuated the LR
    - name: StepFunCosineAnnealingLR
      interval: step
      args:
        T_max: ${sub:${mul:${trainer.max_epochs},${dataset.n_samples_per_epoch}},${add:${.....start_global_step},${system.warmup_steps}}}
        min_factor: 0.0333
        update_every_n_steps: ${trainer.annealing_update_every_n_steps}
