# @package _global_
# Owner: jiahuih

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - celsius_mixed_static
  - override /nrm/model@model: celsius_mamba

model:
  init_weights_path: /lustre/fs12/portfolios/nvr/projects/nvr_torontoai_3dscenerecon/users/jiahuih/workspace/nre/init-ckpt/model_7m1t.ckpt
