# @package _global_
# Owner: jiaweir

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /nrm/apps/kelvin_base: _base
  - /nrm/model@model: kelvin_dav3_base
  - /nrm/dataset/trisplit: _ncore_nvs_mixed
  - override /loss/nrm@loss: kelvin_dav3_context

model:
  freeze_encoder: true
  decoder:
    name: point-query-ca-decoder
    xyz_downsample_stride: 2
    grid_center_stride: 8
    use_gt_semantic_mask: true
    ca_depth: 3

system:
  train_num_workers: 8
  train_batch_size: 1

  val_num_workers: 4
  val_batch_size: 2

  test_num_workers: 4
  log_media_every_n_steps_val: 5

  enable_render_global_step: 0
  strategy: "ddp_find_unused_parameters"

  log_novel_view_overrides:
    - sensor_id: camera_front_wide_120fov
      translation_offset: [0.0, 0.0, -5.0]
      rotation_offset: [0.0, 40.0, 0.0, true]
      height: 720

loss:
  # primitive losses (base: sky=1.0, rgb=0.1, distance=1.0, distance_gradient=1.0, semantics=0.01, velocity=1.0)
  primitive_sky_cubemap:
    lambda_: 0.01
  primitive_rgb:
    lambda_: 0.01
  primitive_distance:
    lambda_: 0.01
  primitive_distance_gradient:
    lambda_: 0.01
  primitive_semantics:
    lambda_: 0.01
  primitive_velocity:
    lambda_: 0.01
  # render losses
  rgb:
    fn: "mse"
    reduce:
      name: "mean"
    lambda_: 1.0
    mask_semantic_classes:
      - "~synthetic"
      - "synthetic"
    semantic_lambdas:
      - 1.0
      - 0.25
  lpips:
    fn: "lpips"
    reduce:
      name: "mean"
    lambda_: 0.2
    limit_max_resolution: 512
  distance:
    fn: "depth_inverse_mse"
    reduce:
      name: "mean"
    lambda_: 0.1
    min_distance: 0.1
    max_distance: 50.0
    normalize_by_opacity: True
    allow_missing_supervision: True
    mask_semantic_classes:
      - "~synthetic"
    semantic_lambdas:
      - 1.0
  background:
    fn: "mse"
    reduce:
      name: "mean"
    lambda_: 2.0

shared_config:
  camera_ids:
    - camera_front_wide_120fov
    - camera_cross_left_120fov
    - camera_cross_right_120fov
  nurec_camera_ids:
    - ncore_path: nurec/all.zarr.itar
      camera_id: camera_front_wide_120fov
      unique_sensor_idx: 0
      sample_ratio: 0.3
    - ncore_path: nurec/all.zarr.itar
      camera_id: camera_cross_left_120fov
      unique_sensor_idx: 1
      sample_ratio: 0.3
    - ncore_path: nurec/all.zarr.itar
      camera_id: camera_cross_right_120fov
      unique_sensor_idx: 2
      sample_ratio: 0.3

override_config:
  res_spec:
    config:
      camera_subsampler:
        frame_width: 504
        frame_height: 280
  data_base_path:
    config:
      ncore_json_base_path: "/lustre/fsw/portfolios/av/users/jiahuih/nre_experiments/data/nurec_depth/"