# @package _global_
# Owner: jiahuih

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /nrm/apps/kelvin_base: _base
  - /nrm/model@model: kelvin_dav3_base
  - /nrm/dataset/trisplit: _ncore_nvs_mixed
  - override /loss/nrm@loss: kelvin_dav3_context

system:
  max_epochs: 40

  train_num_workers: 6
  train_batch_size: 2

  val_num_workers: 4
  val_batch_size: 2

  test_num_workers: 4
  log_media_every_n_steps_val: 5
  log_media_subsample: 2

  enable_render_global_step: 1000000

  log_novel_view_overrides:
    - sensor_id: camera_front_wide_120fov
      translation_offset: [0.0, 0.0, -5.0]
      rotation_offset: [0.0, 40.0, 0.0, true]
      height: 720

dataset:
  train:
    mixture:
      ncore_gen3c_wide:
        sample_ratio: 1.0

shared_config:
  camera_ids:
    - camera_front_wide_120fov
  nurec_camera_ids:
    - ncore_path: nurec/all.zarr.itar
      camera_id: camera_front_wide_120fov
      unique_sensor_idx: 0
      sample_ratio: 0.3

override_config:
  res_spec:
    config:
      # 60-70% MEM with batch size = 2.
      camera_subsampler:
        frame_width: 784
        frame_height: 448
  context_camera_spec:
    config:
      frame_batch_samplers:
        uniform:
          n_frames_per_sample: 18
  data_base_path:
    config:
      ncore_json_base_path: /lustre/fsw/portfolios/av/projects/av_alpamayo_cosmos/users/jiahuih/nre_experiments/data/celsius_6cam_720p_all_in_one
      aux_data:
        depth: /lustre/fsw/portfolios/av/projects/av_alpamayo_cosmos/users/jiahuih/nre_experiments/data/depths/nurec_depth_combined_lidar/{{clip_id}}/{{clip_id}}.aux.depth.zarr.itar
