# @package _global_
# Owner: Haithem Turki

dataset:
  # evaluation setup from SplatAD/NeurAD paper
  camera_mask_border:
    back_camera: [0, 0, 260, 0]

  camera_ids:
    - front_camera
    - left_camera
    - right_camera
    - front_left_camera
    - front_right_camera
    - back_camera
  lidar_ids:
    - main_pandar64

  n_val_image_subsample: 1

  samplers:
    batch_sampler:
      camera_pixel_sampler:
        crop_type: full_image
        subsample: 1

# A lower position lr and higher number of background points seems to work better
model:
  layers:
    background:
      initialization:
        num_point_cloud_points: 2_000_000
      optimizer:
        params:
          positions:
            args:
              lr: 0.00003
      schedulers:
        positions:
          args:
            lr_init: 0.00003
            lr_final: 0.0000003
    dynamic_rigids:
      optimizer:
        params:
          positions:
            args:
              lr: 0.00003
      schedulers:
        positions:
          args:
            lr_init: 0.00003
            lr_final: 0.0000003

system:
  test:
    video_fps: 10
