name: individual-step-time-input-embedding

# The embedding outputs an `n_dims`-dimensional vector, with each dimension being a
# staircase function w.r.t. time.
# Each staircase function has `n_steps` steps, and the step transition point is learned.
n_steps: 1
n_dims: 4
# Whether to learn the step transition point.
requires_grad: true
# The steepness of the step function is controlled by beta, representing the timestamps_us
# required to go from one step to the next.
# We support an annealing strategy where the steepness increases as training progresses
# so that the transition point can be located more accurately.
beta:   # Goes from 5s to 0.5s
  start_timestamps_us: 5000000
  end_timestamps_us: 500000
  start_global_step: 500
  end_global_step: 5000

# Reference to trainer config for adjusting values based on world size
trainer: ${trainer}