defaults:
  - /model/gaussians/composite/_saturate_radiance_mixin

  - /model/gaussians/strategy@strategy: gsplat

  # Background (key = background)
  - /model/gaussians/models@layers.background: sh_gaussians
  - /model/gaussians/initialization@layers.background.initialization: lidar_rig_trajectory

  # Road (key = road)
  - /model/gaussians/models@layers.road: sh_gaussians
  - /model/gaussians/initialization@layers.road.initialization: lidar_rig_trajectory_road

  # Moving rigid cars (key = dynamic_rigids)
  - /model/gaussians/models@layers.dynamic_rigids: rigid_gaussians
  - /model/gaussians/initialization@layers.dynamic_rigids.initialization: lidar_dynamic_tracks
  - /model/tracks_calib@layers.dynamic_rigids.tracks_calib: direct

  # Dynamic deformable objects (key = dynamic_deformables)
  - /model/gaussians/models@layers.dynamic_deformables: deformable_gaussians
  - /model/gaussians/initialization@layers.dynamic_deformables.initialization: lidar_dynamic_tracks
  - /model/tracks_calib@layers.dynamic_deformables.tracks_calib: direct

  - /model/gaussians/renderer@renderer: 3dgut_nrend

name: gaussians-composite
debug_viz: false

train_num_rays: 9999999999 # TODO refactor, add compatibility check
log_to_prog_bar: true # if enabled, include statistics on the Gaussians in the console log

layers:
  dynamic_rigids:
    tracks:
      label_classes:
        [
          "automobile",
          "bus",
          "Bus",
          "Car",
          "Emergency Vehicle",
          "heavy_truck",
          "Medium-sized Truck",
          "Other Vehicle - Construction Vehicle",
          "Other Vehicle - Pedicab",
          "Other Vehicle - Uncommon",
          "other_vehicle",
          "Pickup Truck",
          "protruding_object",
          "Rolling Containers",
          "Semi-truck",
          "Towed Object",
          "trailer",
          "Train",
          "train_or_tram_car",
          "Tram / Subway",
          "Trolley",
          "trolley_bus",
          "vehicle",
        ]
      is_dynamic: true
    initialization:
      symmetric_axis: "Y"
  dynamic_deformables:
    tracks:
      label_classes:
        [
          "animal",
          "Animals - Bird",
          "Animals - Other Animals",
          "bicycle",
          "Bicycle",
          "bicycle_with_rider",
          "cycle",
          "cyclist",
          "CYCLIST",
          "motorcycle",
          "Motorcycle",
          "motorcycle_with_rider",
          "Motorized Scooter",
          "Pedestrian with Object",
          "pedestrian",
          "Pedestrian",
          "person",
          "person_group",
          "Personal mobility device",
          "rider",
          "stroller",
        ]
      is_dynamic: true
    initialization:
      symmetric_axis: null
  background:
    ignore_classes_from_layers: ["road"]
  road:
    class_labels: ["road"]
    scale_pos_lr_by_scene_extent: false
    optimizer:
      params:
        scales:
          args:
            lr: 0.001
