name: sky-env-map
composite_in_linear_space: false
width: 512
height: 512
should_inpaint: true
inpaint_threshold: 5e-2
inpaint_kernel_size: 10
envmap_type: cubemap # choices [equirectangular, cubemap]
saturate_radiance: ${model.saturate_radiance}

# Number of iterations before we start tracking gradients,
# which we use for determining where we inpaint the environment map,
# ideally after the geometry converges a bit
min_grad_updates: 1000
