# @package _global_
# Owner: jiahuih

# This include the mixed data and progressive resolution upsampling configuration.
# The data includes protoplus-motion and slow-motion (selected slow non-high-speed subset from c2).
# Include this in your default list to apply.
defaults:
  - /nrm/dataset@dataset.train.epoch_0: mixed
  - /nrm/dataset/concrete@dataset.train.epoch_0.mixture.ncore_c1_pp.config: ncore_c1_pp_motion
  - /nrm/dataset/concrete@dataset.train.epoch_0.mixture.ncore_c2_slow.config: ncore_c2_slow

  - /nrm/dataset@dataset.train.epoch_5: mixed
  - /nrm/dataset/concrete@dataset.train.epoch_5.mixture.ncore_c1_pp.config: ncore_c1_pp_motion
  - /nrm/dataset/concrete@dataset.train.epoch_5.mixture.ncore_c2_slow.config: ncore_c2_slow

  - /nrm/dataset@dataset.val.epoch_0: mixed
  - /nrm/dataset/concrete@dataset.val.epoch_0.mixture.ncore_c1_pp.config: ncore_c1_pp_motion
  - /nrm/dataset/concrete@dataset.val.epoch_0.mixture.ncore_c2_slow.config: ncore_c2_slow_small

  - /nrm/dataset@dataset.val.epoch_5: mixed
  - /nrm/dataset/concrete@dataset.val.epoch_5.mixture.ncore_c1_pp.config: ncore_c1_pp_motion
  - /nrm/dataset/concrete@dataset.val.epoch_5.mixture.ncore_c2_slow.config: ncore_c2_slow_small

  - /nrm/dataset@dataset.test: mixed
  - /nrm/dataset/concrete@dataset.test.mixture.ncore_c2_slow.config: ncore_c2_slow

shared_config:
  camera_ids:
    - camera_front_wide_120fov
    - camera_cross_left_120fov
    - camera_cross_right_120fov

override_config:
  # Dataset Sample ratio
  ncore_c1_pp_train_sample_ratio:
    selector: ["dataset.train.*ncore_c1_pp"]
    config:
      sample_ratio: 2.0
  ncore_c1_pp_val_sample_ratio:
    selector: ["dataset.val.*ncore_c1_pp"]
    config:
      sample_ratio: 0.7
  ncore_c2_slow_sample_ratio:
    selector: ["dataset.*ncore_c2_slow"]
    config:
      sample_ratio: 0.1

  # Context & Supervision
  context_camera_spec:
    selector: ["dataset.*config"]
    config:
      context_camera_ids: ${shared_config.camera_ids}
      frame_batch_samplers:
        uniform:
          n_frames_per_sample: 6
      supervision_camera_ids: ${shared_config.camera_ids}

  low_res_spec:
    selector: ["dataset.*epoch_0.*config"]
    config:
      supervision_frame_batch:
        prepend_timestamps_us: 100000
        append_timestamps_us: 100000
        n_frames_per_sample: 12
      camera_subsampler:
        frame_width: 416
        frame_height: 240

  high_res_spec:
    selector: ["dataset.*epoch_5.*config", "dataset.test.*config"]
    config:
      supervision_frame_batch:
        prepend_timestamps_us: 100000
        append_timestamps_us: 100000
        n_frames_per_sample: 6
      camera_subsampler:
        frame_width: 960
        frame_height: 544
