# @package _global_
# Owner: jiahuih

# This include the mixed data and progressive resolution upsampling configuration.
# The data includes protoplus, moose (selected subset from c2) and gen3c.
# Include this in your default list to apply.
defaults:
  - /nrm/dataset@dataset.train.epoch_0: mixed
  - /nrm/dataset/concrete@dataset.train.epoch_0.mixture.ncore_c1_pp.config: ncore_c1_pp_train
  - /nrm/dataset/concrete@dataset.train.epoch_0.mixture.ncore_c2_moose.config: ncore_c2_moose
  - /nrm/dataset/concrete@dataset.train.epoch_0.mixture.ncore_c2_gen3c.config: ncore_c2_gen3c

  - /nrm/dataset@dataset.train.epoch_5: mixed
  - /nrm/dataset/concrete@dataset.train.epoch_5.mixture.ncore_c1_pp.config: ncore_c1_pp_train
  - /nrm/dataset/concrete@dataset.train.epoch_5.mixture.ncore_c2_moose.config: ncore_c2_moose
  - /nrm/dataset/concrete@dataset.train.epoch_5.mixture.ncore_c2_gen3c.config: ncore_c2_gen3c

  - /nrm/dataset@dataset.val.epoch_0: mixed
  - /nrm/dataset/concrete@dataset.val.epoch_0.mixture.ncore_c1_pp.config: ncore_c1_pp_val
  - /nrm/dataset/concrete@dataset.val.epoch_0.mixture.ncore_c2_moose.config: ncore_c2_moose_small
  - /nrm/dataset/concrete@dataset.val.epoch_0.mixture.ncore_c2_gen3c.config: ncore_c2_gen3c_small

  - /nrm/dataset@dataset.val.epoch_5: mixed
  - /nrm/dataset/concrete@dataset.val.epoch_5.mixture.ncore_c1_pp.config: ncore_c1_pp_val
  - /nrm/dataset/concrete@dataset.val.epoch_5.mixture.ncore_c2_moose.config: ncore_c2_moose_small
  - /nrm/dataset/concrete@dataset.val.epoch_5.mixture.ncore_c2_gen3c.config: ncore_c2_gen3c_small

  - /nrm/dataset/concrete@dataset.test: ncore_c2_moose

shared_config:
  camera_ids:
    - camera_front_wide_120fov
    - camera_cross_left_120fov
    - camera_cross_right_120fov
  gen3c_additional_camera_ids:
    - ncore_path: gen3c/0.zarr.itar
      camera_id: camera_front_wide_120fov
      unique_sensor_idx: 0
    - ncore_path: gen3c/4.zarr.itar
      camera_id: camera_front_wide_120fov
      unique_sensor_idx: 0
  gen3c_camera_ids: ${add:${.camera_ids},${.gen3c_additional_camera_ids}}

override_config:
  # Dataset Sample ratio
  ncore_c1_pp_sample_ratio:
    selector: ["dataset.*ncore_c1_pp"]
    config:
      sample_ratio: 0.7
  ncore_c2_moose_sample_ratio:
    selector: ["dataset.*ncore_c2_moose"]
    config:
      sample_ratio: 0.025
  ncore_c2_gen3c_sample_ratio:
    selector: ["dataset.*ncore_c2_gen3c"]
    config:
      sample_ratio: 0.1

  # Context
  context_camera_spec:
    selector: ["dataset.*config"]
    config:
      context_camera_ids: ${shared_config.camera_ids}
      frame_batch_samplers:
        uniform:
          n_frames_per_sample: 6

  # Supervision
  regular_camera_spec:
    # Start with dataset, ends with config, but without gen3c inside
    selector: ["^(?!.*gen3c)dataset.*config"]
    config:
      supervision_camera_ids: ${shared_config.camera_ids}

  gen3c_camera_spec:
    selector: ["dataset.*gen3c.*config"]
    config:
      supervision_camera_ids: ${shared_config.gen3c_camera_ids}

  low_res_spec:
    selector: ["dataset.*epoch_0.*config"]
    config:
      supervision_frame_batch:
        prepend_timestamps_us: 100000
        append_timestamps_us: 100000
        n_frames_per_sample: 12
      camera_subsampler:
        frame_width: 416
        frame_height: 240

  high_res_spec:
    selector: ["dataset.*epoch_5.*config"]
    config:
      supervision_frame_batch:
        prepend_timestamps_us: 100000
        append_timestamps_us: 100000
        n_frames_per_sample: 6
      camera_subsampler:
        frame_width: 960
        frame_height: 544
