# @package _global_
# Owner: jiahuih

defaults:
  - /nrm/dataset@dataset.train: mixed
  - /nrm/dataset@dataset.train.mixture.ncore_c1c2kl.config: ncore
  - /nrm/dataset@dataset.train.mixture.ncore_gen3c_wide.config: ncore
  - /nrm/dataset@dataset.train.mixture.sdg_drivesim.config: ncore

  - /nrm/dataset@dataset.val: mixed
  - /nrm/dataset@dataset.val.mixture.ncore_c1c2kl.config: ncore
  - /nrm/dataset@dataset.val.mixture.ncore_gen3c_wide.config: ncore

shared_config:
  camera_ids:
    - camera_front_wide_120fov
    - camera_cross_left_120fov
    - camera_cross_right_120fov
    - camera_rear_left_70fov
    - camera_rear_right_70fov
  nurec_camera_ids:
    - ncore_path: nurec/all.zarr.itar
      camera_id: camera_front_wide_120fov
      unique_sensor_idx: 0
      sample_ratio: 0.3
    - ncore_path: nurec/all.zarr.itar
      camera_id: camera_cross_left_120fov
      unique_sensor_idx: 1
      sample_ratio: 0.3
    - ncore_path: nurec/all.zarr.itar
      camera_id: camera_cross_right_120fov
      unique_sensor_idx: 2
      sample_ratio: 0.3
    - ncore_path: nurec/all.zarr.itar
      camera_id: camera_rear_left_70fov
      unique_sensor_idx: 3
      sample_ratio: 0.3
    - ncore_path: nurec/all.zarr.itar
      camera_id: camera_rear_right_70fov
      unique_sensor_idx: 4
      sample_ratio: 0.3
  gen3c_wide_camera_ids: ${add:${.camera_ids},${.nurec_camera_ids}}

dataset:
  train:
    mixture:
      ncore_c1c2kl:
        sample_ratio: 0.1
        config:
          ncore_json_list_path: s3@pdx-team-ncore://nrm-training-data/celsius_6cam_720p_all_in_one/data-split/equal91/train-c1c2kl.lst
      ncore_gen3c_wide:
        sample_ratio: 0.1
        config:
          ncore_json_list_path: s3@pdx-team-ncore://nrm-training-data/celsius_6cam_720p_all_in_one/data-split/equal91/train-gen3c.lst
      sdg_drivesim:
        sample_ratio: 0.0   # Disabled by default (1.0 will lead to similar number of samples as ncore_c1c2kl)
        config:
          ncore_json_base_path: s3@pdx-team-ncore://nrm-training-data/celsius_6cam_720p_all_in_one/celsius2_mar_ds
          s3_block_size_mb: 16
          s3_cache_type: blockcache
          ncore_json_list_path: s3@pdx-team-ncore://nrm-training-data/celsius_6cam_720p_all_in_one/data-split/all/drivesim.lst
          camera_id_mapping:
            camera_front_wide_120fov: camera_frontwide
            camera_cross_left_120fov: camera_crossleft
            camera_cross_right_120fov: camera_crossright
            camera_rear_left_70fov: camera_rearleft
            camera_rear_right_70fov: camera_rearright
          lidar_id_mapping:
            lidar_gt_top_p128: virtual
          cuboid_tracks_params:
            track_label_source: "GT_SYNTHETIC"
  val:
    mixture:
      ncore_c1c2kl:
        sample_ratio: 0.1
        config:
          ncore_json_list_path: s3@pdx-team-ncore://nrm-training-data/celsius_6cam_720p_all_in_one/data-split/equal91/val-c1c2kl.lst
      ncore_gen3c_wide:
        sample_ratio: 0.1
        config:
          ncore_json_list_path: s3@pdx-team-ncore://nrm-training-data/celsius_6cam_720p_all_in_one/data-split/equal91/val-gen3c.lst

override_config:

  # Data paths
  data_base_path:
    selector: ["dataset.*ncore.*config"]
    config:
      ncore_json_base_path: s3@pdx-team-ncore://nrm-training-data/celsius_6cam_720p_all_in_one/
      s3_block_size_mb: 16
      s3_cache_type: blockcache

  # Context
  context_camera_spec:
    selector: ["dataset.*config"]
    config:
      context_camera_ids: ${shared_config.camera_ids}
      compute_rendering_data: false
      frame_batch_samplers:
        uniform:
          n_frames_per_sample: 8
  regular_context_camera_spec:  # Itemize it to be overriden by children configs
    selector: ["dataset.*config"]
    config:
      frame_batch_samplers:
        uniform:
          frame_gap_timestamp_us: 500000

  # Supervision
  regular_camera_spec:
    # Start with dataset, ends with config, but without gen3c inside
    selector: ["^(?!.*gen3c)dataset.*config"]
    config:
      supervision_camera_ids: ${shared_config.camera_ids}
  gen3c_wide_camera_spec:
    selector: ["dataset.*gen3c_wide.*config"]
    config:
      supervision_camera_ids: ${shared_config.gen3c_wide_camera_ids}

  res_spec:
    selector: ["dataset.*config"]
    config:
      supervision_frame_batch:
        prepend_timestamps_us: 100000
        append_timestamps_us: 100000
        n_frames_per_sample: 6
        camera_subsampler:
          frame_width: 1296
          frame_height: 720
      camera_subsampler:
        frame_width: 504
        frame_height: 280
