# @package _global_
# Owner: jiahuih

# We only use ncore_c1c2kl (no gen3c since time length is not enough), and only low resolution.
defaults:
  - /nrm/dataset@dataset.train: ncore
  - /nrm/dataset@dataset.val: ncore
  - /nrm/dataset@dataset.test: ncore

shared_config:
  camera_ids:
    - camera_front_wide_120fov
    - camera_cross_left_120fov
    - camera_cross_right_120fov
    - camera_rear_left_70fov
    - camera_rear_right_70fov

override_config:

  data_split_path_train:
    selector: ["dataset.train"]
    config:
      ncore_json_list_path: s3@pdx-team-ncore://nrm-training-data/celsius_6cam_720p_all_in_one/data-split/equal91/train-c1c2kl.lst

  data_split_path_test_val:
    selector: ["dataset.val", "dataset.test"]
    config:
      ncore_json_list_path: s3@pdx-team-ncore://nrm-training-data/celsius_6cam_720p_all_in_one/data-split/equal91/val-c1c2kl.lst

  # Context & Supervision for initialization
  init_low_res_spec:
    selector: ["dataset.train", "dataset.val", "dataset.test"]
    config:
      ncore_json_base_path: s3@pdx-team-ncore://nrm-training-data/celsius_6cam_720p_all_in_one/
      s3_block_size_mb: 2
      camera_subsampler:
        frame_width: 416
        frame_height: 240
      supervision_camera_ids: ${shared_config.camera_ids}
      supervision_frame_batch:
        prepend_timestamps_us: 100000
        append_timestamps_us: 100000
        n_frames_per_sample: 24
      context_camera_ids: ${shared_config.camera_ids}
      frame_batch_samplers:
        uniform:
          n_frames_per_sample: 18   # 9s chunk
          n_samples_per_sequence: 1
      # During the high-resolution training stage, since we load too many frames the data loading worker easily OOMs.
      # We have to defer the rendering data computation to the training loop.
      compute_rendering_data: false
