# @package _global_
# Owner: jiahuih

# This include the mixed data and progressive resolution upsampling configuration.
# The data includes protoplus, moose (selected subset from c2) and gen3c.
# Include this in your default list to apply.
defaults:
  - /nrm/dataset@dataset.train.epoch_0: mixed
  - /nrm/dataset@dataset.train.epoch_0.mixture.ncore_c1c2kl.config: ncore
  - /nrm/dataset@dataset.train.epoch_0.mixture.ncore_gen3c.config: ncore

  - /nrm/dataset@dataset.train.epoch_5: mixed
  - /nrm/dataset@dataset.train.epoch_5.mixture.ncore_c1c2kl.config: ncore
  - /nrm/dataset@dataset.train.epoch_5.mixture.ncore_gen3c.config: ncore

  - /nrm/dataset@dataset.val.epoch_0: mixed
  - /nrm/dataset@dataset.val.epoch_0.mixture.ncore_c1c2kl.config: ncore
  - /nrm/dataset@dataset.val.epoch_0.mixture.ncore_gen3c.config: ncore

  - /nrm/dataset@dataset.val.epoch_5: mixed
  - /nrm/dataset@dataset.val.epoch_5.mixture.ncore_c1c2kl.config: ncore
  - /nrm/dataset@dataset.val.epoch_5.mixture.ncore_gen3c.config: ncore

  - /nrm/dataset@dataset.test: mixed
  - /nrm/dataset@dataset.test.mixture.ncore_c1c2kl.config: ncore
  - /nrm/dataset@dataset.test.mixture.ncore_gen3c.config: ncore

shared_config:
  camera_ids:
    - camera_front_wide_120fov
    - camera_cross_left_120fov
    - camera_cross_right_120fov
    - camera_front_tele_30fov
    - camera_rear_left_70fov
    - camera_rear_right_70fov
  gen3c_additional_camera_ids:
    - ncore_path: gen3c/0.zarr.itar
      camera_id: camera_front_wide_120fov
      unique_sensor_idx: 0
    - ncore_path: gen3c/4.zarr.itar
      camera_id: camera_front_wide_120fov
      unique_sensor_idx: 0
  gen3c_camera_ids: ${add:${.camera_ids},${.gen3c_additional_camera_ids}}

override_config:

  # Data paths
  data_base_path:
    selector: ["dataset.*config"]
    config:
      ncore_json_base_path: s3@pdx-team-ncore://nrm-training-data/celsius_6cam_720p_all_in_one/
      s3_block_size_mb: 2

  data_split_path_train:
    selector: ["dataset.train.*ncore_c1c2kl.config"]
    config:
      ncore_json_list_path: s3@pdx-team-ncore://nrm-training-data/celsius_6cam_720p_all_in_one/data-split/equal91/train-c1c2kl.lst

  data_split_path_train_gen3c:
    selector: ["dataset.train.*ncore_gen3c.config"]
    config:
      ncore_json_list_path: s3@pdx-team-ncore://nrm-training-data/celsius_6cam_720p_all_in_one/data-split/equal91/train-gen3c.lst

  data_split_path_test_val:
    selector: ["dataset.val.*ncore_c1c2kl.config", "dataset.test.*ncore_c1c2kl.config"]
    config:
      ncore_json_list_path: s3@pdx-team-ncore://nrm-training-data/celsius_6cam_720p_all_in_one/data-split/equal91/val-c1c2kl.lst

  data_split_path_test_val_gen3c:
    selector: ["dataset.val.*ncore_gen3c.config", "dataset.test.*ncore_gen3c.config"]
    config:
      ncore_json_list_path: s3@pdx-team-ncore://nrm-training-data/celsius_6cam_720p_all_in_one/data-split/equal91/val-gen3c.lst

  # Dataset Sample ratio
  c1c2kl_sample_ratio:
    selector: ["dataset.*ncore_c1c2kl"]
    config:
      sample_ratio: 0.1
  gen3c_sample_ratio:
    selector: ["dataset.*ncore_gen3c"]
    config:
      sample_ratio: 0.1

  # Context
  context_camera_spec:
    selector: ["dataset.*config"]
    config:
      context_camera_ids: ${shared_config.camera_ids}
      frame_batch_samplers:
        uniform:
          n_frames_per_sample: 6
      # During the high-resolution training stage, since we load too many frames the data loading worker easily OOMs.
      # We have to defer the rendering data computation to the training loop.
      compute_rendering_data: false

  # Supervision
  regular_camera_spec:
    # Start with dataset, ends with config, but without gen3c inside
    selector: ["^(?!.*gen3c)dataset.*config"]
    config:
      supervision_camera_ids: ${shared_config.camera_ids}

  gen3c_camera_spec:
    selector: ["dataset.*gen3c.*config"]
    config:
      supervision_camera_ids: ${shared_config.gen3c_camera_ids}

  low_res_spec:
    selector: ["dataset.*epoch_0.*config"]
    config:
      supervision_frame_batch:
        prepend_timestamps_us: 100000
        append_timestamps_us: 100000
        n_frames_per_sample: 12
      camera_subsampler:
        frame_width: 416
        frame_height: 240

  high_res_spec:
    selector: ["dataset.*epoch_5.*config"]
    config:
      supervision_frame_batch:
        prepend_timestamps_us: 100000
        append_timestamps_us: 100000
        n_frames_per_sample: 6
      camera_subsampler:
        frame_width: 800
        frame_height: 448
