# @package _global_
# Owner: jiahuih

defaults:
  - /nrm/dataset/concrete@dataset.train: ncore_local_low_res
  - /nrm/dataset/concrete@dataset.val: ncore_local_low_res
  - /nrm/dataset/concrete@dataset.test: ncore_local_low_res

# Expose frequently altered configs.
shared_config:
  camera_ids:
    - camera_front_wide_120fov
    - camera_cross_left_120fov
    - camera_cross_right_120fov
  frame_width: 416
  frame_height: 240
  supervision_frame_width: ${shared_config.frame_width}
  supervision_frame_height: ${shared_config.frame_height}
  supervision_frames_per_sample: 12
  n_samples_per_sequence: 50
  n_frames_per_sample: 6

override_config:
  ncore_low_res_spec:
    selector: ["dataset.train", "dataset.val", "dataset.test"]
    config:
      camera_subsampler:
        frame_width: ${shared_config.frame_width}
        frame_height: ${shared_config.frame_height}
      context_camera_ids: ${shared_config.camera_ids}
      frame_batch_samplers:
        uniform:
          n_frames_per_sample: ${shared_config.n_frames_per_sample}
          n_samples_per_sequence: ${shared_config.n_samples_per_sequence}
      supervision_frame_batch:
        camera_subsampler:
          frame_width: ${shared_config.supervision_frame_width}
          frame_height: ${shared_config.supervision_frame_height}
        n_frames_per_sample: ${shared_config.supervision_frames_per_sample}
      compute_rendering_data: false
