# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@mypy_integration//:mypy.bzl", "mypy_test")
load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")

package(default_visibility = ["//visibility:private"])

py_binary(
    name = "nvs_ncore",
    srcs = ["nvs_ncore.py"],
    data = [
        "//configs",
    ],
    main = "nvs_ncore.py",
    package_collisions = "ignore",
    deps = [
        "//nre/artifact:pylib",
        "//nre/render:pylib",
        "//nre/utils:pylib",
        "//nre/utils/io/export:pylib_render",
        "//nre/viewer:pylib",
        pip_requirement("click"),
        pip_requirement("s3fs"),
        pip_requirement("tqdm"),
        pip_requirement("nvidia-ncore"),
        pip_requirement("nvidia-ncore-internal"),
        pip_requirement("hydra-core"),
    ],
)

mypy_test(
    name = "nrm_data_mypy",
    timeout = "long",
    deps = [
        ":nvs_ncore",
    ],
)
