# SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//bazel/pytest:defs.bzl", "pytest_test")

package(default_visibility = ["//:core_package_group"])

filegroup(
    name = "py_files",
    srcs = glob(["**/*.py"]) + [
        "//libs/losses/models/lambda_schedulers:py_files",
        "//libs/losses/models/reduce_functions:py_files",
    ],
)

py_library(
    name = "pylib",
    srcs = [
        "__init__.py",
        "base_losses.py",
        "cuda_losses_module.py",
        "loss_fns.py",
        "losses_module.py",
        "primitive_losses.py",
        "registry.py",
        "render_losses.py",
        "utils.py",
    ],
    deps = [
        "//libs/losses/functional:pylib",
        "//libs/losses/kernel:def_constants",
        "//libs/losses/models/lambda_schedulers:pylib",
        "//libs/losses/models/reduce_functions:pylib",
        "//libs/slang_gaussians:pylib",
        "//nre/datasets:pylib",
        "//nre/models:pylib",
        "//nre/models/base:pylib",
        "//nre/models/gaussians:pylib",
        "//nre/models/gaussians:pylib_gaussians_composite",
        "//nre/nrm/models:pylib",
        "//nre/nrm/primitives:pylib",
        "//nre/utils:pylib",
        pip_requirement("einops"),
        pip_requirement("fused-ssim"),
        pip_requirement("omegaconf"),
        pip_requirement("torch"),
    ],
)

pytest_test(
    name = "loss_fns_test",
    srcs = ["loss_fns_test.py"],
    deps = [
        ":pylib",
        pip_requirement("fused-ssim"),
    ],
)

pytest_test(
    name = "render_losses_test",
    srcs = ["render_losses_test.py"],
    deps = [
        ":pylib",
        pip_requirement("omegaconf"),
    ],
)

pytest_test(
    name = "cuda_losses_module_test",
    srcs = ["cuda_losses_module_test.py"],
    deps = [
        ":pylib",
        pip_requirement("omegaconf"),
    ],
)

pytest_test(
    name = "losses_module_test",
    size = "large",
    srcs = ["losses_module_test.py"],
    deps = [
        ":pylib",
        "//libs/losses/orchestration:pylib",
        "//nre/config:pylib",
        pip_requirement("omegaconf"),
    ],
)

pytest_test(
    name = "cuda_slang_losses_equivalence_test",
    size = "large",
    srcs = ["cuda_slang_losses_equivalence_test.py"],
    deps = [
        ":pylib",
        "//libs/losses/functional:pylib_with_slang",
    ],
)
