name: nrm-dataverse

frame_batch_samplers:
  varying_interval:
    name: varying_interval
    n_frames_per_sample: 4  # NB [JW]: use 4 frames per sample to align with TokenGS.
    n_samples_per_sequence: 1
    sequence_gap_timestamp_us_min: 45
    sequence_gap_timestamp_us_max: 192

supervision_frame_batch:
  n_frames_per_sample: 4
  prepend_timestamps_us: 0
  append_timestamps_us: 0
  sample_strategy: "random"

camera_subsampler:
  frame_width: 256
  frame_height: 256

subset_spec:
  target: "re10k.RealEstate10K"
  root_path: ???
  annotation_json: ???
