name: ???
local_debug_dir: null # Path to local directory for storing debug ply files
scale_multiplier: ${eval:'0.2 if ("${model.strategy.name}"=="mcmc") else 1.0'} # Set to multiply the scale of the gaussians - used in MCMC strategy