defaults:
  - base

name: nrm-ply
translate_world_to_nre: true # Whether to translate the positions from world to NRE coordinates
path: ??? # the path to the ply file

# Number of points to use from nrm
num_point_cloud_points: 3_000_000

density_pruning:
  enabled: false
  keep: ${..num_point_cloud_points} # Only keep the top N points with the highest densities
  density_threshold: null # 0.1 # Only keep points with densities greater than this threshold

# Lidarfree car2sim uses:
# init background: 650k + 100k + 100k = 850k
# init road: 400k
# init dynamic rigids: 300k
# init dynamic deformables: 300k
# initstatic rigids: 150k
# init total: 2.0M
# total: 2.3M