defaults:
  - base

name: ply-tracks
transform: [[1, 0, 0, 0], [0, 0, -1, 0], [0, 1, 0, 0], [0, 0, 0, 1]]
scale_to_track: true
track_ids: ???
fallback:
  name: lidar-dynamic-tracks

  num_point_cloud_points: 1_000

  default_density: ${eval:'0.5 if ("${model.strategy.name}"=="mcmc") else 0.1'}
  default_scale: 0.1
  symmetric_axis: Y