# NRM Celsius-p16b16_2.0.0-6f3c pretrained model living at NGC

model_url: https://api.ngc.nvidia.com/v2/org/nvstaging/team/nre/models/nrm-celsius/versions/c200p16b16_6f3c/files/c200p16b16_6f3c.ckpt
model_config: https://api.ngc.nvidia.com/v2/org/nvstaging/team/nre/models/nrm-celsius/versions/c200p16b16_6f3c/files/c200p16b16_6f3c.yaml
model_config_overrides:
  # Allow easy switching test dataset by overriding this option.
  - +nrm/dataset/concrete@dataset.test=ncore_local_low_res
  - +model.renderer.prepare_before_render=False # add missing config entry for backward compatibility
  - +model.activations.xyz_type=none

model_cache_dir: ${oc.env:HOME}/.cache/nrm/pretrained_models/c200p16b16_6f3c # update as required
