model_url: https://api.ngc.nvidia.com/v2/org/nvstaging/team/nre/models/nrm-kelvin-pa/versions/0.1.0-varying/files/nrm-kelvin-pa_0.1.0-varying.ckpt
model_config: https://api.ngc.nvidia.com/v2/org/nvstaging/team/nre/models/nrm-kelvin-pa/versions/0.1.0-varying/files/nrm-kelvin-pa_0.1.0-varying.yaml
model_config_overrides: []
  
model_cache_dir: ${oc.env:HOME}/.cache/nrm/pretrained_models/kelvin_pa_front
