# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//bazel/slang:defs.bzl", "slangtorch_library")

package(default_visibility = ["//:core_package_group"])

filegroup(
    name = "py_files",
    srcs = glob(["**/*.py"]),
)

filegroup(
    name = "slang_files",
    srcs = glob(["*.slang"]),
)

filegroup(
    name = "transform_slang_files",
    srcs = ["transform.slang"],
)

# Compile the Pose Slang module into a SlangTorch C++ CUDA extension
slangtorch_library(
    name = "pose_kernels_slang_cc",
    srcs = ["pose_kernels.slang"],
    extra_cmd_args = (
        "-I$$(dirname $$(dirname $$(dirname $(location pose.slang)))) " +
        "-I$$(dirname $$(dirname $(location //libs/slang_utils:extensions_slang))) " +
        "-I$$(dirname $$(dirname $(location //libs/slang_utils:constants_slang)))"
    ),
    deps = [
        "pose.slang",
        "quaternion.slang",
        "transform.slang",
        "//libs/geometry/kernels:slang_files",
        "//libs/slang_utils:constants_slang",
        "//libs/slang_utils:extensions_slang",
    ],
)

py_library(
    name = "interface",
    srcs = ["interface.py"],
    deps = [
        ":pose_kernels_slang_cc",
        pip_requirement("torch"),
    ],
)

py_library(
    name = "pose_utils",
    srcs = ["pose.py"],
    deps = [
        ":interface",
        pip_requirement("torch"),
    ],
)

py_library(
    name = "pylib",
    srcs = [
        "__init__.py",
    ],
    deps = [
        ":interface",
        ":pose_kernels_slang_cc",
        ":pose_utils",
        "//libs/slang_utils:pylib_utils",
        pip_requirement("torch"),
    ],
)
