defaults:
  - celsius_static

# Add additional vehicle RGB supervision (for non-synthetic views)
rgb:
  mask_semantic_classes: ["~synthetic", "synthetic", "(~synthetic)&vehicle"]
  semantic_lambdas: [1.0, 0.25, 1.0]

# Add additional vehicle distance supervision + go from road to valid regions
distance:
  mask_semantic_classes: ["~synthetic", "synthetic", "(~synthetic)&vehicle"]
  semantic_lambdas: [1.0, 0.25, 1.0]

primitive_velocity:
  fn: mse
  reduce:
    name: mean
  lambda_: 0.1

primitive_sigma:
  fn: bce_truncated
  reduce:
      name: mean
  lambda_: 0.01
