# Use context loss as base
defaults:
  - kelvin_dav3_context

rgb:
  fn: mse
  reduce:
    name: mean
  lambda_: 1.0
  # Use lower weight for synthetic views
  # For static models, hood and dynamic objects will be marked as invalid.
  mask_semantic_classes: ["~synthetic", "synthetic"]
  semantic_lambdas: [1.0, 0.25]

# SSIM is disabled in favor of LPIPS loss,
# and we add this loss no matter the view is synthetic or not
lpips:
  fn: lpips
  reduce:
    name: mean
  lambda_: 0.2
  limit_max_resolution: 512

distance:
  fn: depth_inverse_mse
  reduce:
    name: mean
  lambda_: 0.1
  min_distance: 0.1
  max_distance: 50.0
  normalize_by_opacity: true
  allow_missing_supervision: true
  mask_semantic_classes: ["~synthetic"]
  semantic_lambdas: [1.0]

background:
  fn: mse
  reduce:
    name: mean
  lambda_: 2.0

# Context are either disabled or regularization only.
primitive_sky_cubemap:
  lambda_: 0.01

primitive_rgb:
  lambda_: 0.01

primitive_distance_gradient:
  lambda_: 0.01

# Semantics, normal, and velocity are not changed.
