defaults:
  - base

name: so

train_batch_size: 1

train_num_workers: 24
val_num_workers: 8
test_num_workers: 8
update_n_epochs: 0 # NB: we're leveraging PL's Trainer `reload_dataloaders_every_n_epochs` option, therefore we can't set this for each sampler individually

mock_dataloader: false # for benchmarking purposes

prefetch:  # GPU data prefetching using background thread
  enabled: false
  queue_size: 2  # Number of batches to prefetch ahead