# Copyright (c) 2023-2025 NVIDIA CORPORATION.  All rights reserved.

#
# BUILD & PUSH: Please refer to build_dev_python_docker.sh
# LOCAL_RUN: docker run --rm -it --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 --privileged nre:[TAG] [COMMAND]
#   (optionally mount NRE codebase by adding -v .:/workspace)
#
# Note: this image is used for running the Cluster toolbox on ORD in 'docker_python' mode
#       Please do not to overwrite existing images!

FROM nvidia/cuda:12.8.0-devel-ubuntu22.04

LABEL maintainer="Jiahui Huang <jiahuih@nvidia.com>"

# Needed for string substitution
ENV DEBIAN_FRONTEND=noninteractive

# Set required driver capabilities ('compute' for cuda, 'graphics' for optix, 'utility' for nvidia-smi)
ENV NVIDIA_DRIVER_CAPABILITIES=graphics,compute,utility

# Make all devices visible by default
ENV NVIDIA_VISIBLE_DEVICES=all

RUN \
    # Add additional system libraries
    apt-get update -qq --fix-missing && \
    apt-get install -y --no-install-recommends software-properties-common && \
    add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
    apt-get -y update -qq --fix-missing && \
    apt-get -y install --no-install-recommends \
        gcc g++ gcc-11 g++-11 libglib2.0-0 libopenblas-dev libcublas11 libgl1 clang git wget xz-utils jq sudo pandoc jupyter-nbconvert python3-pip patchelf docker.io openssh-client \
    && \
    rm -rf /var/lib/apt/lists/*

# Create foreign docker groups to allow access to host's /var/run/docker.sock
RUN \
    groupadd --gid 141 docker141 && \
    groupadd --gid 999 docker999

# Install Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    bash /tmp/miniconda.sh -b -p /opt/conda && \
    rm /tmp/miniconda.sh

# Active the conda environment (SHELL commands will be prepended to all subsequent RUNs)
ENV PATH="/opt/conda/bin:$PATH"
SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]

# The following logic should mainly follow the one in external/install-env.sh
RUN conda install -y python=3.11 && conda clean --all -y

# Clone the NRE repo
WORKDIR /tmp
# (Before cloning, we need to add host key to known_hosts)
RUN mkdir -p /root/.ssh && ssh-keyscan -H gitlab-master.nvidia.com >> /root/.ssh/known_hosts
ARG REPO_COMMIT
RUN --mount=type=ssh ssh-add -l && git clone ssh://git@gitlab-master.nvidia.com:12051/nrs/nre.git && \
    cd nre && git checkout ${REPO_COMMIT}

# We need to use the private registry (add --secret id=netrc,src=$HOME/.netrc to your docker image build command)
WORKDIR /tmp/nre
RUN --mount=type=secret,id=netrc,target=/root/.netrc \
    pip install --no-cache-dir -r deps/python/requirements_3_11_internal_x86_64.txt

# Additional pip packages:
RUN pip install --no-cache-dir ninja "cmake<4.0"
# Install mamba for LongLRM (https://arxiv.org/abs/2410.12781)
# (Not in requirements.txt for now since both installation and dep-check requires torch as prerequisite)
RUN pip install --no-cache-dir git+https://github.com/Dao-AILab/causal-conv1d.git
RUN pip install --no-cache-dir --no-build-isolation git+https://github.com/state-spaces/mamba.git

ENV TORCH_CUDA_ARCH_LIST="8.0;8.6;8.9;9.0;10.0;12.0;12.0+PTX"
RUN pip install nre/models/post_processings/bilateral_grid/cuda
RUN pip install libs/vren
RUN pip install libs/packed_ops
RUN pip install libs/gaussian_mcmc
RUN pip install libs/pytorch3d_knn
RUN pip install libs/ray_utils
RUN NREND_FORCE_DEVICE_CC=80 pip install libs/nrend     # Allow maximum compatibility

# Set the working directory and entrypoint (and some clean-up)
WORKDIR /workspace
RUN rm -rf /tmp/*

# Add to bashrc so that when user use bash (using interactive mode -i) the environment will be activated
RUN conda init bash --user
