# @package _global_
# Owner: Haithem Turki

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base
  - /trainer: base
  - /dataset: ncore
  - /datamodule: so

  # Background (key = background)
  # Moving rigid cars (key = dynamic_rigids)
  # Moving deformable objects (key = dynamic_deformables)
  - /model: gaussians/composite/dynamic_gaussians

  - /model/calib: skip
  - /difix: difix
  - /model/background: sky_mlp
  - /system: gaussians
  - /loss: gaussians_av
  - /model/post_processing@model.post_processing.b: bilateral_grid_per_camera
  - /model/post_processing@model.post_processing.c: bilateral_grid_per_frame

  - override /dataset/samplers: timestamp_image_crop # important for scaling gradients in densification buffers, SSIM loss and performance

dataset:
  valid_measurements_method: EGO
  n_samples_per_epoch: 30000

trainer:
  precision: 32
  check_val_every_n_epoch: 1
