# @package _global_
# Owner: Haithem Turki

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base
  - /trainer: base
  - /dataset: ncore
  - /datamodule: so
  - /model: gaussians/composite/static_gaussians
  - /model/calib: skip
  - /model/background: sky_mlp
  - /difix: difix
  - /system: gaussians
  - /loss: gaussians_av
  - /model/post_processing@model.post_processing.b: bilateral_grid_per_camera
  - /model/post_processing@model.post_processing.c: bilateral_grid_per_frame
  - override /dataset/samplers: timestamp_image_crop # important for scaling gradients in densification buffers, SSIM loss and performance

trainer:
  precision: 32
  check_val_every_n_epoch: 1

dataset:
  n_samples_per_epoch: 30000