# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@mypy_integration//:mypy.bzl", "mypy_test")
load("@nre_pip_deps//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("@rules_python//python/entry_points:py_console_script_binary.bzl", "py_console_script_binary")
load("//bazel/pytest:defs.bzl", "pytest_test")

package(default_visibility = [":__subpackages__"])

py_binary(
    name = "run_cluster_toolbox",
    srcs = [
        "run_cluster_toolbox.py",
    ],
    data = [
        "//internal/workflows/cluster_toolbox/cluster_configs",
        "//internal/workflows/cluster_toolbox/job_templates",
        "//internal/workflows/cluster_toolbox/wandb_sweep_configs",
        "@maglev_cli//file:maglev",
    ],
    main = "run_cluster_toolbox.py",
    deps = [
        "pylib",
        "//nre/config:pylib_version",
        "//nre/utils:pylib_misc",
    ],
)

py_library(
    name = "pylib",
    srcs = [
        "__init__.py",
        "base_toolbox.py",
        "maglev_toolbox.py",
        "ngc_toolbox.py",
        "ord_toolbox.py",
        "utils.py",
    ],
    deps = [
        requirement("hydra-core"),
        requirement("click"),
        requirement("wandb"),
        requirement("shortuuid"),
        "//internal/workflows:pylib",
        "//internal/workflows/cluster_toolbox/job_templates/ord:pylib",
        "@rules_python//python/runfiles",
    ],
)

mypy_test(
    name = "run_cluster_toolbox_mypy",
    timeout = "long",
    deps = [
        ":run_cluster_toolbox",
    ],
)

pytest_test(
    name = "maglev_toolbox_test",
    srcs = [
        "maglev_toolbox_test.py",
    ],
    data = [
        "@maglev_cli//file:maglev",
    ],
    deps = [
        ":pylib",
    ],
)

# Make `wandb` cli script available as target
py_console_script_binary(
    name = "wandb",
    pkg = "@nre_pip_deps//wandb",
)
