# @package _global_
# Owner: Haithem Turki

dataset:
  val_lidar: true

model:
  background:
    should_inpaint: false

  layers:
    background:
      initialization:
        num_point_cloud_points: 2000000

system:
  test:
    metrics:
      ssim:
        enabled: true
      lpips:
        enabled: true

    lidar:
      save_renders:
        enabled: true

loss: 
  lidar:
    lambda_: 0.005
  intensity:
    lambda_: 0.1
  raydrop:
    lambda_: 0.05
  sky_env_map_background:
    lambda_: 1e-4
