# @package _global_
# Owner: Haithem Turki

model:
  # Not currently using the deformation network for Simuli - we can revisit and see if it's worth the quality-rendering speed trade-off.
  layers:
    dynamic_rigids:
      tracks:
        label_classes:
          [
            "animal",
            "Animals - Bird",
            "Animals - Other Animals",
            "automobile",
            "bicycle",
            "Bicycle",
            "bicycle_with_rider",
            "bus",
            "Bus",
            "Car",
            "cycle",
            "cyclist",
            "CYCLIST",
            "Emergency Vehicle",
            "heavy_truck",
            "Medium-sized Truck",
            "motorcycle",
            "Motorcycle",
            "motorcycle_with_rider",
            "Motorized Scooter",
            "Other Vehicle - Construction Vehicle",
            "Other Vehicle - Pedicab",
            "Other Vehicle - Uncommon",
            "other_vehicle",
            "Pedestrian with Object",
            "pedestrian",
            "Pedestrian",
            "person",
            "person_group",
            "Personal mobility device",
            "Pickup Truck",
            "protruding_object",
            "rider",
            "Rolling Containers",
            "Semi-truck",
            "stroller",
            "Towed Object",
            "trailer",
            "Train",
            "train_or_tram_car",
            "Tram / Subway",
            "Trolley",
            "trolley_bus",
            "vehicle",
          ]
    dynamic_deformables:
      tracks:
        label_classes: []
