# @package _global_
# Owner: Haithem Turki

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /apps/AV/PandaSet/3dgut_dynamic_mcmc.yaml
  - _simuli_mixin.yaml
  - _simuli_dynamic_mixin.yaml
  - /model/gaussians/extra_signal@model.layers.background.extra_signal: [intensity, raydrop]
  - /model/gaussians/extra_signal@model.layers.dynamic_rigids.extra_signal: [intensity, raydrop]
  - override /model/background: sky_env_map

model:
  background:
    width: 4096
    height: 4096

dataset:
  lidar_ignore_rows: [62, 63]

loss:
  bilateral_grid_per_frame_spatial_tv:
    lambda_: 0
  bilateral_grid_per_frame_temporal_tv:
    lambda_: 0
  bilateral_grid_per_camera_tv:
    lambda_: 0
  bilateral_grid_drift:
    lambda_: 0
