# @package _global_
# Owner: Haithem Turki

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /apps/AV/Waymo/3dgut_static_mcmc.yaml
  - _simuli_mixin.yaml
  - _simuli_waymo_mixin.yaml
  - /model/gaussians/extra_signal@model.layers.background.extra_signal: [intensity, raydrop]
  - override /model/background: sky_env_map
