# @package _global_

dataset:
  # Reduction factor of rendered frame resolution w.r.t. input resolution
  # It makes sense to set this to the same as the subsampling used during training to avoid aliasing,
  # but it can also be increased w.r.t. training for validation speed up.
  n_val_image_subsample: 2
  val_camera_frame_step: 1  # Validation on every camera frame (10 fps camera -> 10 fps predictions)
  val_lidar_frame_step: 1

system:
  test:
    save_results: true
    save_inputs: true
    save_videos: true
    video_fps: 10
