# SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@aspect_rules_py//py:defs.bzl", "py_binary", "py_image_layer")

# nre:allow-py-venv-binary - py_venv_binary used for better perf and multiprocess-safety of deliverables
load("@aspect_rules_py//py/unstable:defs.bzl", "py_venv_binary")
load("@bazel_skylib//rules:run_binary.bzl", "run_binary")
load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_load", "oci_push")
load("@rules_pkg//:pkg.bzl", "pkg_tar")
load("//bazel/rules_oci:default_layer_groups.bzl", "default_layer_groups")

filegroup(
    name = "tools_list",
    srcs = ["tools.yaml"],
)

# by default, install all tools
# debugpy / pydantic are included for generating the runtime version string
NRE_TOOLS_DEPS = [
    pip_requirement("click"),
    pip_requirement("click-default-group"),
    "//nre/config:pylib_version",
    "//nre:pylib",
] + select({
    "//bazel/conditions:all_tools": [
        "//apps/aux_gen:pylib",
    ],
    "//bazel/conditions:ncore_aux_data": [
        "//apps/aux_gen:pylib",
    ],
    "//conditions:default": [],
}) + select({
    "//bazel/conditions:all_tools": [
        "//apps/avmask_annotator:pylib",
    ],
    "//bazel/conditions:mask_annotator": [
        "//apps/avmask_annotator:pylib",
    ],
    "//conditions:default": [],
}) + select({
    "//bazel/conditions:all_tools": [
        "//apps/asset_harvester:pylib",
    ],
    "//bazel/conditions:asset_harvester": [
        "//apps/asset_harvester:pylib",
    ],
    "//conditions:default": [],
})

NRE_TOOLS_DATA = [
    "//:notices_file",
] + select({
    "//bazel/conditions:asset_harvester": [
        "//apps/asset_harvester:asset_harvester_data_lib",
    ],
    "//conditions:default": [],
})

################################################################
# Common image rules
################################################################

# Layer for HOME directory writable by all users
# (ex. to receive default cache folder for various Python dependencies, though
# this won't be persisted in our typical container invocations).
pkg_tar(
    name = "home_dir_tar",
    compressor = "@pigz//:pigz",
    empty_dirs = ["/home"],
    extension = "tar.gz",
    mode = "0777",
    tags = [
        "manual",
    ],
)

################################################################
# Obfuscation rules
################################################################

# The doc for py_image_layer states that "binary" should be a py_binary target. However, the implementation is
# not Python-specific, so we can use it with the "pycena_nre_tools" target.
py_image_layer(
    name = "pycena_nre_tools_image_layer",
    compressor = "@pigz//:pigz",
    compressor_args = "-n",
    layer_groups = default_layer_groups(),
    root = "/app/",
    tags = [
        "manual",
        "no-remote-cache",
    ],
)

oci_image(
    name = "obfuscated_nre_tools_image_oci",
    base = "@nre_run_image_oci",
    entrypoint = ["/app/internal/scripts/pycena/runtime/pycena_nre_tools"],
    env = {
        "HOME": "/home",
        "TORCHINDUCTOR_CACHE_DIR": "/tmp/torchinductor",
    },
    tags = [
        "manual",
        "no-remote-cache",
    ],
    tars = [
        ":pycena_nre_tools_image_layer",
        ":home_dir_tar",
        "//bazel/version:version_file_yaml_tar",  # put last in the list of tar files to make this the last / often changing layer
    ],
)

# Build the image and load it into a local runtime:
# $ bazel run //apps:load_obfuscated_nre_tools_image_oci
# $ docker run -it --rm --gpus all nvcr.io/nvidian/ct-toronto-ai/nre_obfuscated_tools:latest
oci_load(
    name = "load_obfuscated_nre_tools_image_oci",
    image = ":obfuscated_nre_tools_image_oci",
    repo_tags = ["nvcr.io/nvidian/ct-toronto-ai/nre_obfuscated_tools:latest"],
    tags = [
        "manual",
        "no-remote-cache",
    ],
)

# Push the image to the registry:
# $ bazel run //apps:push_obfuscated_nre_tools_image_oci [-- --tag ${TAG}]
# Note: Don't push the 'latest' tag from local builds, we reserve this to images generated by post-merge pipelines in CI.
#       A custom tag can be specific on the above command if needed.
oci_push(
    name = "push_obfuscated_nre_tools_image_oci",
    image = ":obfuscated_nre_tools_image_oci",
    repository = "nvcr.io/nvidian/ct-toronto-ai/nre_obfuscated_tools",  # this can be overriden by providing --repository
    tags = [
        "manual",
        "no-remote-cache",
    ],
)

################################################################
# Normal container rules
################################################################

# OCI image for 'nre_tools'
py_image_layer(
    name = "nre_tools_image_layer",
    binary = "nre_tools",
    compressor = "@pigz//:pigz",
    compressor_args = "-n",
    layer_groups = default_layer_groups(),
    root = "/app/",
    tags = [
        "manual",
        "no-remote-cache",
    ],
)

oci_image(
    name = "nre_tools_image_oci",
    base = "@nre_run_image_oci",
    entrypoint = ["/app/apps/nre_tools"],
    env = {
        "HOME": "/home",
        "TORCHINDUCTOR_CACHE_DIR": "/tmp/torchinductor",
    },
    tags = [
        "manual",
        "no-remote-cache",
    ],
    tars = [
        ":nre_tools_image_layer",
        ":home_dir_tar",
        "//bazel/version:version_file_yaml_tar",
    ],
)

# Build the image and load it into a local runtime:
# $ bazel run //apps:load_nre_tools_image_oci
# $ docker run -it --rm --gpus all nvcr.io/nvidian/ct-toronto-ai/nre_tools:latest
oci_load(
    name = "load_nre_tools_image_oci",
    image = ":nre_tools_image_oci",
    repo_tags = ["nvcr.io/nvidian/ct-toronto-ai/nre_tools:latest"],
    tags = [
        "manual",
        "no-remote-cache",
    ],
)

# Push the image to the registry:
# $ bazel run //apps:push_nre_tools_image_oci [-- --tag ${TAG}]
# Note: Don't push the 'latest' tag from local builds, we reserve this to images generated by post-merge pipelines in CI.
#       A custom tag can be specific on the above command if needed.
oci_push(
    name = "push_nre_tools_image_oci",
    image = ":nre_tools_image_oci",
    repository = "nvcr.io/nvidian/ct-toronto-ai/nre_tools",  # this can be overriden by providing --repository
    tags = [
        "manual",
        "no-remote-cache",
    ],
)

################################################################
# PyBinary rules
################################################################

py_venv_binary(
    name = "nre_tools",
    srcs = [
        "__init__.py",
        ":entrypoint.py",
    ],
    data = NRE_TOOLS_DATA,
    main = "entrypoint.py",
    visibility = [
        # Add visibility for SQA tests
    ],
    deps = NRE_TOOLS_DEPS,
)

py_binary(
    name = "gen_entrypoint_tool",
    srcs = ["gen_entrypoint.py"],
    main = "gen_entrypoint.py",
    deps = [
        pip_requirement("pyyaml"),
        pip_requirement("jinja2"),
    ],
)

# Generate entrypoint.py based off desired tools
run_binary(
    name = "gen_entrypoint",
    srcs = [
        "templates/entrypoint.py.j2",
        "tools.yaml",
    ],
    outs = ["entrypoint.py"],
    args = [
        "--config=$(location tools.yaml)",
        "--template=$(location templates/entrypoint.py.j2)",
        "--output=$(location entrypoint.py)",
        "--enabled-tools",
    ] + select({
        "//bazel/conditions:all_tools": [
            "ncore-aux-data",
            "mask-annotator",
            "asset-harvester",
        ],
        "//conditions:default": [],
    }) + select({
        "//bazel/conditions:ncore_aux_data": ["ncore-aux-data"],
        "//conditions:default": [],
    }) + select({
        "//bazel/conditions:mask_annotator": ["mask-annotator"],
        "//conditions:default": [],
    }) + select({
        "//bazel/conditions:asset_harvester": ["asset-harvester"],
        "//conditions:default": [],
    }),
    tool = ":gen_entrypoint_tool",
)
