enabled: false
checkpoint:
  enabled: true
  strip_optimizer: false
parsed_config:
  enabled: true
rig_trajectories:
  enabled: true
  add_default_cameras: false
  match_datasource: true
sequence_tracks:
  enabled: true
  controllable_only: false
mesh:
  ground:
    enabled: true
