defaults:
  - base
  - /model/input_embedding@time_input_embedding: skip
  - /model/input_embedding@instance_input_embedding: weighted_instance

name: hash-grid-object
include_xyz: false

output:
  signal_dim: 16
  extra_signal_dim: 0
n_output_dims: ${sum_values:${.output}}

seed: ${seed}
enable_jit_if_supported: false
double_backward_skip_input_grad: true

hash_grid_encoding_config:
  otype: HashGrid
  n_features_per_level: 2
  log2_hashmap_size: 19
  base_resolution: 16
  # For scenes this is 16,4096
  n_levels: 16
  max_resolution: 4096
encoding_interp_config: 
  interp_type: smooth_st_v2  # [linear, smooth, smooth_st, smooth_st_v2]
  lambda_: 2.0
encoding_prog_config:
  n_initial_levels: 10
  update_frequency: 500
  n_levels_per_update: 1
encoding_lod_config: null

mlp_network_config:
  otype: FullyFusedMLP
  activation: ReLU
  output_activation: none
  n_neurons: 64
  n_hidden_layers: 1

# Embedding modules defined in default list.
instance_input_embedding: ???
time_input_embedding: ???
