# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//bazel/pytest:defs.bzl", "pytest_test")

DEFAULT_VISIBILITY = ["//:core_package_group"]

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "py_files",
    srcs = glob(["**/*.py"]),
    visibility = [
    ],
)

py_library(
    name = "pylib_base_schema",
    srcs = ["base_schema.py"],
    deps = [
        pip_requirement("pydantic"),
    ],
)

py_library(
    name = "pylib",
    srcs = [
        "__init__.py",
        "base_schema.py",
    ],
    visibility = DEFAULT_VISIBILITY + [
        # add visibility to //internal/scripts/experimental:ncore_to_ngp
        "//:asset_harvester_package_group",
    ],
    deps = [
        pip_requirement("pydantic"),
        pip_requirement("shortuuid"),
        pip_requirement("nvidia-ncore"),
        ":pylib_base_schema",
        "//instant_nurec/nre/utils:pylib_misc",
    ],
)

