# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:private"])

py_library(
    name = "pylib_kratos",
    srcs = ["kratos_uploader.py"],
    deps = [
        "//nre/config:pylib_version",
        "//nre/utils:pylib_metrics",
        "//nre/visualdebugger:pylib",
        pip_requirement("cloudevents"),
        pip_requirement("kratos_pycloudevents"),
    ],
)

py_binary(
    name = "upload_metrics_to_kratos",
    srcs = ["upload_metrics_to_kratos.py"],
    main = "upload_metrics_to_kratos.py",
    deps = [
        ":pylib_kratos",
        "//nre/utils:pylib_metrics",
        "//nre/visualdebugger:pylib",
        pip_requirement("pyyaml"),
        pip_requirement("click"),
    ],
)

py_library(
    name = "pylib_s3cmd",
    srcs = ["s3cmd_monitor.py"],
    deps = [
        pip_requirement("pyyaml"),
    ],
)

py_library(
    name = "pylib_metrics_monitor",
    srcs = ["metrics_monitor.py"],
    deps = [
        ":pylib_kratos",
        ":pylib_s3cmd",
        pip_requirement("pyyaml"),
        pip_requirement("click"),
    ],
)

py_binary(
    name = "metrics_monitor",
    srcs = ["metrics_monitor.py"],
    main = "metrics_monitor.py",
    deps = [
        ":pylib_metrics_monitor",
    ],
)

py_binary(
    name = "setup_monitor",
    srcs = ["setup_monitor.py"],
    main = "setup_monitor.py",
    deps = [
        ":pylib_metrics_monitor",
        pip_requirement("click"),
    ],
)
