# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@mypy_integration//:rules.bzl", "mypy_stubs")
load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@rules_python//python:defs.bzl", "py_library")

DEFAULT_VISIBILITY = [
    "//:core_package_group",
    "//bazel/docs:__pkg__",
]

package(default_visibility = DEFAULT_VISIBILITY)

filegroup(
    name = "py_files",
    srcs = glob(["**/*.py"]),
    visibility = [
        "//internal/scripts/pycena:__pkg__",
    ],
)

# Proto files for customer distribution
filegroup(
    name = "proto_files",
    srcs = [
        "common.proto",
        "sensorsim.proto",
    ],
    visibility = [
        "//nre/grpc:__pkg__",
        "//nre/grpc/release:__pkg__",
    ],
)

py_library(
    name = "grpc_pb2",
    srcs = [
        ":py_files",
    ],
    visibility = [
        "//nre/datasets/samplers:__pkg__",
        "//nre/grpc:__pkg__",
        "//nre/nrm:__pkg__",
        "//nre/render/novel_trajectory:__pkg__",
        "//nre/utils/io/export:__pkg__",
    ],
    deps = [
        pip_requirement("protobuf"),
        pip_requirement("grpcio"),
        ":grpc_pb2_stubs",
    ],
)

filegroup(
    name = "pyi_files",
    srcs = glob(["**/*.pyi"]),
)

mypy_stubs(
    name = "grpc_pb2_stubs",
    srcs = [
        ":pyi_files",
    ],
)
