# SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary

load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//:core_package_group"])

filegroup(
    name = "py_files",
    srcs = glob(["**/*.py"]),
    visibility = [],
)

py_library(
    name = "pylib",
    srcs = [
        "__init__.py",
        "utils.py",
    ],
    deps = [
        "//nre/utils:pylib_types",
        pip_requirement("torch"),
        pip_requirement("numpy"),
        pip_requirement("pillow"),
    ],
)
