# @package _global_
defaults:
  - /nrm/dataset/concrete@dataset.predict: ncore_local_low_res
  - sensors@dataset.predict: h81_front_784
  - artifact@predict.artifact: base

shared_config:
  n_chunks: 8

system:
  predict_batch_size: ${shared_config.n_chunks}
  predict_num_workers: 4
  num_nodes: 1
  device_count: 1
  strategy: auto

mode: predict

viewer:
  enabled: false
  ray_subsampling_step:
    high_resolution: 0.2
    low_resolution: 0.2

model:
  export_preprocess:
    enabled: true
    density_prune_threshold: 0.01

predict:
  artifact:
    enabled: false
  chunk_size: 1
  primitive_merge:
    enabled: true
    overlap_strategy: frustum_ownership
    frustum_ownership_max_diff_m: 5.0
  export_ply:
    enabled: true
  render_video:
    enabled: true
    depth: false
    override_sensors:
      - sensor_id: camera_front_wide_120fov
        height: 720
      - sensor_id: camera_front_wide_120fov
        height: 720
        translation_offset: [0.0, 0.0, -8.0]
        rotation_offset: [0.0, 40.0, 0.0, true]
        force_pinhole: true

dataset:
  predict:
    ncore_json_list_path: ???
    ncore_json_base_path: ???
    supervision_camera_ids: ${.context_camera_ids}
    supervision_frame_batch:
      n_frames_per_sample: 0 # Disable supervision to save memory
      prepend_timestamps_us: 0
      append_timestamps_us: 0
    frame_batch_samplers:
      uniform:
        enabled: false
      adaptive_sequential:
        enabled: true
        name: adaptive_sequential
        n_frames_per_sample: 18
        n_samples_per_sequence: ${shared_config.n_chunks}
        max_frame_gap_timestamp_us: 750000
    # Load lidar frames -- not needed
    lidar_frame_batch:
      gap_from_image_us: 0

# Specify output directory (save_dir, ckpt_dir etc will change accordingly)
out_dir: /nrm_debug/kelvin_predict
# Dummy logger to avoid cluttering.
logger:
  enabled: false
  name: "dummy"
  # Generate new run ID for each run
  run_id: "<generate>"
