# @package _global_
defaults:
  - /nrm/dataset/concrete@dataset.predict: ncore_local_low_res
  - sensors@dataset.predict: h81_front_960
  - artifact@predict.artifact: base

shared_config:
  # Should cover most sequences if context length is 3s.
  n_chunks: 8
  # Used when lidar is available.
  # If distance aux also exists, lidar would still be loaded but not used.
  lidar_gap_from_image_us: 1000000

system:
  predict_batch_size: ${shared_config.n_chunks}
  predict_num_workers: 4
  num_nodes: 1
  device_count: 1

mode: predict

viewer:
  enabled: false
  ray_subsampling_step:
    high_resolution: 0.5
    low_resolution: 1.0

predict:
  artifact:
    enabled: true
  chunk_size: 1
  primitive_merge:
    enabled: true
    mode: "none"
    # overlap_strategy: "two_sigma"
    overlap_strategy: "frustum_ownership"
    dynamic_sigma_threshold: 1.0
    enable_voxelization: false
    enable_sky_mask: true
  export_ply:
    enabled: true
    falloff_sigma_timestamp_us: -1
    minimum_density: 0.01
    minimum_scale: 0.0  # applied to the smallest scale
    minimum_surface_area: 0.001  # scale x^2 + y^2 + z^2
    maximum_velocity: 0.01

dataset:
  predict:
    supervision_camera_ids: ${.context_camera_ids}
    supervision_frame_batch:
      n_frames_per_sample: 0 # Disable supervision to save memory
      prepend_timestamps_us: 0
      append_timestamps_us: 0
    frame_batch_samplers:
      uniform:
        enabled: false
      sequential:
        name: sequential
        n_frames_per_sample: 6
        n_samples_per_sequence: ${shared_config.n_chunks}
        frame_gap_timestamp_us: 500000
        first_frame_timestamp: 0
        allow_out_of_bounds: true
    # Load lidar frames
    lidar_frame_batch:
      gap_from_image_us: ${shared_config.lidar_gap_from_image_us}

model:
  export_preprocess:
    enabled: true
    density_prune_threshold: 0.01
    # Celsius-only (ignored for Kelvin)
    keep_sky_gaussians: false
    # Project each Gaussian onto the road plane along its spawning ray (Celsius only)
    project_to_z_offset: false
    z_offset: 0.0
    projection: ray
  velocity_from_lidar:
    enabled: true
    gap_from_image_us: ${shared_config.lidar_gap_from_image_us}

# Specify output directory (save_dir, ckpt_dir etc will change accordingly)
out_dir: /nrm_debug/long_primitive_merge
# Dummy logger to avoid cluttering.
logger:
  enabled: false
  name: "dummy"
  # Generate new run ID for each run
  run_id: "<generate>"
