# @package _global_

# Profile training memory and time usage by using a small dataset.

system:
  num_nodes: 1
  device_count: 1
  max_epochs: 1

  train_num_workers: 0
  val_num_workers: 0

  log_every_n_steps: 10000
  log_media_every_n_steps: 10000
  log_media_every_n_steps_val: 10000

profiling:
  enabled: true
  limit_train_val_batches: 2
  scopedtimer: true
  disable_checkpoint: true
  record_memory_history: true

# Validation will give too many events.
mode: train

# Specify output directory (save_dir, ckpt_dir etc will change accordingly)
out_dir: /nrm_debug/profile_training
# Dummy logger to avoid cluttering.
logger:
  enabled: false
  name: "dummy"
  run_id: "<generate>"
