# @package _global_

system:
  num_nodes: 1
  device_count: 1

mode: test

viewer:
  enabled: true
  ray_subsampling_step:
    high_resolution: 1.0
    low_resolution: 1.0

# Specify output directory (save_dir, ckpt_dir etc will change accordingly)
out_dir: /nrm_debug/single_gpu_test
# Dummy logger to avoid cluttering.
logger:
  enabled: false
  name: "dummy"
  # Generate new run ID for each run
  run_id: "<generate>"
