# @package _global_
# Owner: Mu Li

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /apps/AV/_base_3dgut_static.yaml
  - /apps/AV/module_mixins/_mcmc_mixin.yaml
  - /apps/prod/options/artifact: default
  - /apps/prod/options/nrend: disabled
  - /apps/prod/options/difix/3dgut: disabled
  - /apps/prod/options/mesh: disabled
  - /apps/prod/options/ground: disabled
  - override /model/background: skip
  - override /model/gaussians/strategy@model.strategy: mcmc
  - override /model/gaussians/initialization@model.layers.background.initialization: sfm_point_cloud
  - override /model/post_processing@model.post_processing.b: null
  - override /model/post_processing@model.post_processing.c: null
  - override /logger: dummy
  - override /loss: gaussians

dataset:
  lidar_ids:
    - dummy_lidar

  n_train_sample_lidar_rays: 0
  n_val_image_subsample: 1
  n_samples_per_epoch: 30000

  aux_data: false

  samplers:
    batch_sampler:
      camera_pixel_sampler:
        subsample: 1

trainer:
  max_epochs: 1
  check_val_every_n_epoch: 1

model:
  layers:
    background:
      initialization:
        camera_ids: ${dataset.camera_ids}
        lidar_ids: ${dataset.lidar_ids}
  strategy:
    add:
      max_n_gaussians: 1000000
  renderer:
    global_z_order: true
    projection:
      ut_require_all_sigma_points: false

loss:
  gaussian_scale:
    lambda_: 0.01
  gaussian_density:
    lambda_: 0.01

system:
  test:
    metrics:
      cpsnr:
        enabled: false
