# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "pylib_constants",
    srcs = [
        "__init__.py",
        "constants.py",
    ],
    visibility = ["//visibility:public"],
)
