// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.

#pragma once

#include <torch/extension.h>

// RayFlags and other compile-time constants are provided via constants_cuda.h
// (generated by constants.py --header and included in losses_cuda.cu)

#define CHECK_INPUT(x)                                     \
    TORCH_CHECK(x.is_cuda(), #x " must be a CUDA tensor"); \
    TORCH_CHECK(x.is_contiguous(), #x " must be contiguous");

inline uint32_t div_round_up(uint32_t val, uint32_t divisor) {
    return (val + divisor - 1) / divisor;
}

// ============================================================================
// Dispatch 0: Road Gaussians Loss
// ============================================================================

/*!
 * @param positions_world [n_points, 3]
 * @param rotations_world [n_points, 4] - quaternions in xyzw format
 * @param pose_tquat [1, 7] - [tx, ty, tz, qx, qy, qz, qw]
 * @param random_values [n_biases]
 * @param stats [n_biases, 7] (output, pre-allocated)
 * @param total_loss [1] (output, pre-allocated)
 */
void road_gaussians_forward_cuda(
    torch::Tensor const positions_world,
    torch::Tensor const rotations_world,
    torch::Tensor const pose_tquat,
    torch::Tensor const random_values,
    torch::Tensor const stats,
    torch::Tensor const total_loss,
    float min_bias,
    float range_bias,
    float grid_len,
    float rotation_lambda);

void road_gaussians_backward_cuda(
    torch::Tensor const positions_world,
    torch::Tensor const rotations_world,
    torch::Tensor const pose_tquat,
    torch::Tensor const random_values,
    torch::Tensor const stats,
    torch::Tensor const grad_total_loss,
    torch::Tensor const grad_positions_world,
    torch::Tensor const grad_rotations_world,
    float min_bias,
    float range_bias,
    float grid_len,
    float rotation_lambda);

// ============================================================================
// Dispatch 1: Camera Losses
// ============================================================================

/*!
 * @param B_rgb Batch size
 * @param H_rgb Height
 * @param W_rgb Width
 * @param rgb_factor Pre-computed 1/N_valid for mean reduction (-1 = disabled)
 * @param bg_factor Pre-computed 1/N_valid for mean reduction (-1 = disabled)
 * @param rgb_flags [B, H, W, 1] int32
 * @param rgb_gt [B, H, W, 3] float32
 * @param rgb_pred [B, H, W, 3] float32
 * @param bg_pred [N_rays] float32
 * @param rgb_loss [B, H, W] float32 (output, pre-allocated)
 * @param bg_loss [N_rays] float32 (output, pre-allocated)
 */
void camera_losses_forward_cuda(
    int B_rgb, int H_rgb, int W_rgb,
    float rgb_factor, float bg_factor,
    torch::Tensor const rgb_flags,
    torch::Tensor const rgb_gt,
    torch::Tensor const rgb_pred,
    torch::Tensor const bg_pred,
    torch::Tensor const rgb_loss,
    torch::Tensor const bg_loss);

void camera_losses_backward_cuda(
    int B_rgb, int H_rgb, int W_rgb,
    float rgb_factor, float bg_factor,
    torch::Tensor const rgb_flags,
    torch::Tensor const rgb_gt,
    torch::Tensor const rgb_pred,
    torch::Tensor const bg_pred,
    torch::Tensor const grad_rgb_loss,
    torch::Tensor const grad_bg_loss,
    torch::Tensor const grad_rgb_pred,
    torch::Tensor const grad_bg_pred);

// ============================================================================
// Dispatch 2: LiDAR Losses
// ============================================================================

/*!
 * @param B_lidar Batch size
 * @param H_lidar Height
 * @param W_lidar Width
 * @param lidar_factor, bg_lidar_factor, intensity_factor, raydrop_factor  Pre-computed 1/N_valid (-1 = disabled)
 * @param FLAG_INVALID, FLAG_DROPPED, FLAG_SKY_SEMANTIC, FLAG_DIFIXED, FLAG_SYNTHETIC  RayFlags values
 * @param lidar_flags [B, H, W, 1] int32
 * @param lidar_gt [B, H, W, 1] float32
 * @param intensity_gt [B, H, W, 1] float32
 * @param raydrop_gt [B, H, W, 1] float32
 * @param lidar_pred [B, H, W, 1] float32
 * @param bg_lidar_pred [N_rays_lidar] float32
 * @param intensity_pred [B, H, W, 1] float32
 * @param raydrop_pred [B, H, W, 1] float32
 * @param lidar_loss [B, H, W] float32 (output)
 * @param bg_lidar_loss [N_rays_lidar] float32 (output)
 * @param intensity_loss [B, H, W] float32 (output)
 * @param raydrop_loss [B, H, W] float32 (output)
 */
void lidar_losses_forward_cuda(
    int B_lidar, int H_lidar, int W_lidar,
    float lidar_factor, float bg_lidar_factor, float intensity_factor, float raydrop_factor,
    torch::Tensor const lidar_flags,
    torch::Tensor const lidar_gt,
    torch::Tensor const intensity_gt,
    torch::Tensor const raydrop_gt,
    torch::Tensor const lidar_pred,
    torch::Tensor const bg_lidar_pred,
    torch::Tensor const intensity_pred,
    torch::Tensor const raydrop_pred,
    torch::Tensor const lidar_loss,
    torch::Tensor const bg_lidar_loss,
    torch::Tensor const intensity_loss,
    torch::Tensor const raydrop_loss);

void lidar_losses_backward_cuda(
    int B_lidar, int H_lidar, int W_lidar,
    float lidar_factor, float bg_lidar_factor, float intensity_factor, float raydrop_factor,
    torch::Tensor const lidar_flags,
    torch::Tensor const lidar_gt,
    torch::Tensor const intensity_gt,
    torch::Tensor const raydrop_gt,
    torch::Tensor const lidar_pred,
    torch::Tensor const bg_lidar_pred,
    torch::Tensor const intensity_pred,
    torch::Tensor const raydrop_pred,
    torch::Tensor const grad_lidar_loss,
    torch::Tensor const grad_bg_lidar_loss,
    torch::Tensor const grad_intensity_loss,
    torch::Tensor const grad_raydrop_loss,
    torch::Tensor const grad_lidar_pred,
    torch::Tensor const grad_bg_lidar_pred,
    torch::Tensor const grad_intensity_pred,
    torch::Tensor const grad_raydrop_pred);

// ============================================================================
// Dispatch 3: Gaussian Regularization Losses
// ============================================================================

/*!
 * @param N_scales, N_densities, N_z_scales, N_oob  Element counts per sub-loss
 * @param scale_factor, density_factor, z_scale_factor, z_scale_threshold, oob_factor  Factors
 * @param gaussian_scales [N_scales, 3] float32 (pre-activation log-space)
 * @param gaussian_densities [N_densities] float32
 * @param gaussian_z_scales [N_z_scales, 3] float32 (pre-activation log-space)
 * @param oob_positions [N_oob, 3] float32
 * @param oob_cuboid_dims [N_oob, 3] float32 (non-differentiable)
 * @param scale_loss [N_scales] float32 (output)
 * @param density_loss [N_densities] float32 (output)
 * @param z_scale_loss [N_z_scales] float32 (output)
 * @param oob_loss [N_oob] float32 (output)
 */
void gaussian_losses_forward_cuda(
    int N_scales, int N_densities, int N_z_scales, int N_oob,
    float scale_factor, float density_factor, float z_scale_factor, float z_scale_threshold, float oob_factor,
    torch::Tensor const gaussian_visibility,
    torch::Tensor const gaussian_scales,
    torch::Tensor const gaussian_densities,
    torch::Tensor const gaussian_z_scales,
    torch::Tensor const oob_positions,
    torch::Tensor const oob_cuboid_dims,
    torch::Tensor const scale_loss,
    torch::Tensor const density_loss,
    torch::Tensor const z_scale_loss,
    torch::Tensor const oob_loss);

void gaussian_losses_backward_cuda(
    int N_scales, int N_densities, int N_z_scales, int N_oob,
    float scale_factor, float density_factor, float z_scale_factor, float z_scale_threshold, float oob_factor,
    torch::Tensor const gaussian_visibility,
    torch::Tensor const gaussian_scales,
    torch::Tensor const gaussian_densities,
    torch::Tensor const gaussian_z_scales,
    torch::Tensor const oob_positions,
    torch::Tensor const oob_cuboid_dims,
    torch::Tensor const grad_scale_loss,
    torch::Tensor const grad_density_loss,
    torch::Tensor const grad_z_scale_loss,
    torch::Tensor const grad_oob_loss,
    torch::Tensor const grad_gaussian_scales,
    torch::Tensor const grad_gaussian_densities,
    torch::Tensor const grad_gaussian_z_scales,
    torch::Tensor const grad_oob_positions);

// ============================================================================
// Dispatch 4: Background Texture & Grid Regularization Losses
// ============================================================================

/*!
 * @param B_tex, D_tex, H_tex, W_tex, C_tex  Background texture dimensions
 * @param B_gc, D_gc, H_gc, W_gc  Camera grid dimensions
 * @param B_gf, D_gf, H_gf, W_gf  Frame grid dimensions
 * @param bg_tex_factor  Sky env map TV factor
 * @param grid_drift_camera_factor, grid_drift_frame_factor  Grid drift factors
 * @param grid_camera_tv_factor, grid_frame_tv_factor  Grid spatial TV factors
 * @param bg_tex [B*D, H, W, C] float32
 * @param grids_camera [B_gc*12, D, H, W] float32
 * @param grids_frame [B_gf*12, D, H, W] float32
 * @param bg_tex_loss [B*D*H*W*C] float32 (output)
 * @param grids_drift_loss [numel_gc + numel_gf] float32 (output)
 * @param grid_camera_tv_loss [numel_gc] float32 (output)
 * @param grid_frame_tv_loss [numel_gf] float32 (output)
 */
void background_grid_losses_forward_cuda(
    int B_tex, int D_tex, int H_tex, int W_tex, int C_tex,
    int B_gc, int D_gc, int H_gc, int W_gc,
    int B_gf, int D_gf, int H_gf, int W_gf,
    float bg_tex_factor,
    float grid_drift_camera_factor, float grid_drift_frame_factor,
    float grid_camera_tv_factor, float grid_frame_tv_factor,
    torch::Tensor const bg_tex,
    torch::Tensor const grids_camera,
    torch::Tensor const grids_frame,
    torch::Tensor const bg_tex_loss,
    torch::Tensor const grids_drift_loss,
    torch::Tensor const grid_camera_tv_loss,
    torch::Tensor const grid_frame_tv_loss);

void background_grid_losses_backward_cuda(
    int B_tex, int D_tex, int H_tex, int W_tex, int C_tex,
    int B_gc, int D_gc, int H_gc, int W_gc,
    int B_gf, int D_gf, int H_gf, int W_gf,
    float bg_tex_factor,
    float grid_drift_camera_factor, float grid_drift_frame_factor,
    float grid_camera_tv_factor, float grid_frame_tv_factor,
    torch::Tensor const bg_tex,
    torch::Tensor const grids_camera,
    torch::Tensor const grids_frame,
    torch::Tensor const grad_bg_tex_loss,
    torch::Tensor const grad_grids_drift_loss,
    torch::Tensor const grad_grid_camera_tv_loss,
    torch::Tensor const grad_grid_frame_tv_loss,
    torch::Tensor const grad_bg_tex,
    torch::Tensor const grad_grids_camera,
    torch::Tensor const grad_grids_frame);
