# SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@aspect_rules_py//py:defs.bzl", "py_binary", "py_library")
load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("//bazel/pytest:defs.bzl", "pytest_test")

DEFAULT_VISIBILITY = ["//:core_package_group"]

package(default_visibility = DEFAULT_VISIBILITY)

py_library(
    name = "pylib",
    srcs = [
        "artifacts.py",
        "commands.py",
        "datasets.py",
        "resource.py",
        "test_cases.py",
        "train_val_configs.py",
    ],
    data = [
        "test_plan.yml",
        "//internal/sqa/edit-assets:samples",
        "//internal/sqa/edit-assets:testdata",
        "//internal/sqa/scripts",
    ],
    visibility = DEFAULT_VISIBILITY + [
        "//internal/sqa:__pkg__",
    ],
    deps = [
        pip_requirement("pyyaml"),
    ],
)

pytest_test(
    name = "test_test_cases_integrity",
    srcs = ["test_test_cases_integrity.py"],
    data = [
        "//configs",
        "//internal/sqa:README.md",
    ],
    deps = [
        ":pylib",
    ],
)

py_library(
    name = "sync_test_plan_lib",
    srcs = [
        "sync_test_plan.py",
    ],
    data = [
        ":defs.bzl",
        "//internal/sqa:README.md",
    ],
    deps = [
        ":pylib",
        pip_requirement("click"),
    ],
)

py_binary(
    name = "sync_test_plan",
    srcs = [
        "sync_test_plan.py",
    ],
    main = "sync_test_plan.py",
    deps = [
        ":sync_test_plan_lib",
    ],
)

pytest_test(
    name = "sync_test_plan_test",
    srcs = [
        "sync_test_plan_test.py",
    ],
    deps = [
        ":sync_test_plan_lib",
    ],
)
