# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

"""Test plan information generated by sync_test_plan.py, do not modify manually."""

LITE_TEST_CASES = [
    {"executable": "//:run", "name": "nre_image_render--mode-lite--obfuscation-no--dataset-test_data_ncore--artifact_source-test_data_ncore_sqa_default_25.06_artifacts", "parallel_execution": True, "resources": ["@test_data_ncore//:ncore_clipgt_1sec", "@test_data_ncore_sqa_default_25.06_artifacts//:all"]},
    {"executable": "//:run", "name": "nre_image_render--mode-lite--obfuscation-no--dataset-test_data_ncore--config-hyperion8.1_sqa_default--artifact_source-train_val", "parallel_execution": True, "resources": ["@test_data_ncore//:ncore_clipgt_1sec"]},
    {"executable": "//:run", "name": "nre_image_trainval--mode-lite--obfuscation-no--dataset-test_data_ncore--config-hyperion8.1_sqa_default", "parallel_execution": False, "resources": ["@test_data_ncore//:ncore_clipgt_1sec"]},
    {"executable": "//internal/scripts/pycena/runtime:pycena_run", "name": "nre_image_trainval--mode-lite--obfuscation-yes--dataset-test_data_ncore--config-hyperion8.1_sqa_default", "parallel_execution": True, "resources": ["@test_data_ncore//:ncore_clipgt_1sec"]},
    {"executable": "//:run", "name": "nre_render_grpc--mode-lite--obfuscation-no--dataset-test_data_ncore--artifact_source-test_data_ncore_sqa_default_25.06_artifacts", "parallel_execution": True, "resources": ["@test_data_ncore//:ncore_clipgt_1sec", "@test_data_ncore_sqa_default_25.06_artifacts//:all"]},
    {"executable": "//:run", "name": "nre_render_grpc--mode-lite--obfuscation-no--dataset-test_data_ncore--config-hyperion8.1_sqa_default--artifact_source-train_val", "parallel_execution": True, "resources": ["@test_data_ncore//:ncore_clipgt_1sec"]},
    {"executable": "//:run", "name": "nre_render_grpc--mode-lite--obfuscation-no--dataset-test_data_ncore--config-hyperion8.1_sqa_default--artifact_source-train_val--edit_assets_scenario-sqa_scene_lite", "parallel_execution": True, "resources": ["@test_data_ncore//:ncore_clipgt_1sec"]},
    {"executable": "//:run", "name": "nre_render_grpc--mode-lite--obfuscation-no--dataset-test_data_ncore--config-hyperion8.1_sqa_default--artifact_source-train_val--test_control_actor-yes", "parallel_execution": True, "resources": ["@test_data_ncore//:ncore_clipgt_1sec"]},
    {"executable": "//:run", "name": "nre_render_grpc--mode-lite--obfuscation-no--dataset-test_data_ncore--config-hyperion8.1_sqa_default--artifact_source-train_val--use_gsplat-yes", "parallel_execution": True, "resources": ["@test_data_ncore//:ncore_clipgt_1sec"]},
    {"executable": "//apps:nre_tools", "name": "nre_tools--mode-lite--obfuscation-no--dataset-test_data_ncore", "parallel_execution": True, "resources": ["@test_data_ncore//:ncore_clipgt_1sec"]},
    {"executable": "//internal/scripts/pycena/runtime:pycena_nre_tools", "name": "nre_tools--mode-lite--obfuscation-yes--dataset-test_data_ncore", "parallel_execution": True, "resources": ["@test_data_ncore//:ncore_clipgt_1sec"]},
    {"executable": "//:run", "name": "run_example--mode-lite--obfuscation-no--script_filename-example_losses", "parallel_execution": True, "resources": []},
]
