# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@nre_pip_deps//:requirements.bzl", pip_requirement = "requirement")
load("//bazel/pytest:defs.bzl", "pytest_test")

py_binary(
    name = "ppisp_report",
    srcs = ["ppisp_report.py"],
    main = "ppisp_report.py",
    visibility = ["//visibility:public"],
    deps = [
        pip_requirement("click"),
        pip_requirement("torch"),
        pip_requirement("matplotlib"),
        pip_requirement("omegaconf"),
        pip_requirement("numpy"),
        "//nre/models:pylib",
        "//nre/systems:pylib",
    ],
)

pytest_test(
    name = "ppisp_report_test",
    srcs = ["ppisp_report_test.py"],
    deps = [
        ":ppisp_report",
        pip_requirement("torch"),
        pip_requirement("numpy"),
        "//nre/models:pylib",
    ],
)
