# Copyright (c) 2025-2026 NVIDIA CORPORATION.  All rights reserved.

build+test:
  extends: .bazel_test
  stage: build
  tags:
    - type/docker
    - os/linux
    - arch/x86_64
    - gpu
    - 2_gpus
  script:

    # Check code format
    - bazelisk run //:format.check

    # Validate pycena dependencies are up to date
    - bazelisk run //internal/scripts/pycena/runtime:update_deps -- --validate //:run
    - bazelisk run //internal/scripts/pycena/runtime:update_deps -- --validate //apps:nre_tools
    - bazelisk run //internal/scripts/pycena/runtime:update_deps -- --validate //nre/nrm:run

    # Build+test all remaining targets
    - bazelisk build ...
    - bazelisk test ...
  allow_failure: false
