# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

.sqa_lite:
  extends: .bazel_test
  stage: system_tests
  tags:
    - type/docker
    - os/linux
    - arch/x86_64
    - gpu
    - 2_gpus

sqa_lite:
  extends: .sqa_lite
  needs:
    # No need to wait for all jobs from previous stages since these tests don't
    # use Docker, but serialize behind 'build+test' to avoid wasting CI
    # resources if build or unit tests aren't successful.
    - build+test
  script:
    - bazelisk test //internal/sqa:sqa_test_suite --test_arg=--validate_ci_runtime_limits
  allow_failure: false

sqa_lite_docker:
  extends: .sqa_lite
  needs:
    - images
  script:
    - bazelisk test //internal/sqa:sqa_docker_test_suite --test_arg=--tag=${VERSION_STRING}
  rules:
    # Tests in this job don't support Bazel caching, only run nightly or on-demand
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_TYPE == "nightly"
      when: on_success
    - when: manual
  allow_failure: true

sqa_full_forward_rendering:
  extends: .sqa_lite
  needs:
    - images
  script:
    - internal/scripts/ci/rclone_setup.sh
    # Clean up any previous test results to compensate for lack of sandbox from bazel run
    - rm -rf $(bazelisk info bazel-bin)/internal/sqa/run_tests.runfiles/_main/results/
    # Test identifiers are resolved from test_plan.yml via wildcard: all full-mode nre_render_grpc tests using previous release artifacts
    - bazelisk run //internal/sqa:run_tests -- --tag=${VERSION_STRING} --test-identifiers=nre_render_grpc--mode-full*--artifact_source-*_artifacts
  after_script:
    # Follow the convention of keeping test results in "testlogs" directory. Copy the results to "testlogs" because bazel run's results don't end up in "bazel-testlogs" by default
    # Gitlab doesn't dereference symlinks, so copy is necessary
    - rm -rf testlogs
    - mkdir -p testlogs/internal/sqa
    - cp -rL $(bazelisk info bazel-bin)/internal/sqa/run_tests.runfiles/_main/results/* testlogs/internal/sqa/
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_TYPE == "nightly"
      when: on_success
    - when: manual
  allow_failure: true
