# @package _global_
# Owner: jiahuih

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /nrm/apps/celsius_base: _static_full
  - /nrm/dataset/trisplit: _ncore_6cam_pdx
  - override /nrm/model@model: celsius_p16_b16

model:
  init_weights_path: s3@pdx-team-ncore://nrm-training-data/init-ckpt/gslrm_p16_b16.safetensors
  activation_checkpointing: true

system:
  train_num_workers: 32
  val_num_workers: 32
  test_num_workers: 32
