# @package _global_
# Owner: jiahuih

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /nrm/apps/celsius_base: _static_full
  - /nrm/dataset/trisplit: _mixed_data

model:
  init_weights_path: /lustre/fsw/portfolios/nvr/users/jiahuih/workspace/nre/init-ckpt/gslrm.ckpt
  activation_checkpointing: true

shared_config:
  camera_ids:
    - camera_front_wide_120fov

