# @package _global_
# Owner: jiahuih

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /nrm/apps/celsius_base: _static_full
  - /nrm/dataset/trisplit: _ncore_nvs_mixed
  - override /nrm/model@model: celsius_p16_b16

model:
  init_weights_path: s3@pdx-team-ncore://nrm-training-data/init-ckpt/gslrm_p16_b16.safetensors
  activation_checkpointing: true

system:
  train_num_workers: 32
  val_num_workers: 32
  test_num_workers: 32

shared_config:
  camera_ids:
    - camera_front_wide_120fov
    - camera_cross_left_120fov
    - camera_cross_right_120fov
    - camera_rear_left_70fov
    - camera_rear_right_70fov
  nurec_camera_ids:
    - ncore_path: nurec/all.zarr.itar
      camera_id: camera_front_wide_120fov
      unique_sensor_idx: 0
      sample_ratio: 0.3
    - ncore_path: nurec/all.zarr.itar
      camera_id: camera_cross_left_120fov
      unique_sensor_idx: 1
      sample_ratio: 0.3
    - ncore_path: nurec/all.zarr.itar
      camera_id: camera_cross_right_120fov
      unique_sensor_idx: 2
      sample_ratio: 0.3
    - ncore_path: nurec/all.zarr.itar
      camera_id: camera_rear_left_70fov
      unique_sensor_idx: 3
      sample_ratio: 0.3
    - ncore_path: nurec/all.zarr.itar
      camera_id: camera_rear_right_70fov
      unique_sensor_idx: 4
      sample_ratio: 0.3

override_config:
  bump_resolution_at_epoch:
    selector: ["dataset.*config"]
    config:
      augmentations:
        camera_subsampler:
          low_res:
            values:
            - frame_width: 416
              frame_height: 240
            weights: [1.0]
            start_epoch: 0
          high_res:
            values:
            - frame_width: 800
              frame_height: 448
            weights: [1.0]
            start_epoch: 5
