# @package _global_
# Owner: jiahuih

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /nrm/apps/celsius_base: _static_full
  - /nrm/dataset/trisplit: _mixed_data
  - override /nrm/model@model: celsius_p16_b16

model:
  init_weights_path: /lustre/fsw/portfolios/nvr/users/jiahuih/workspace/nre/init-ckpt/gslrm_p16_b16.safetensors
  activation_checkpointing: true
